pentaho/mondrian

src/main/mondrian/olap/MondrianProperties.xml, src/main/mondrian/rolap/SqlMemberSource.java, src/main/mondrian/rolap/SqlTupleReader.java, src/main/mondrian/rolap/agg/SegmentLoader.java, testsrc/main/mondrian/test/BasicQueryTest.java
=> [MONDRIAN-2161] check query cancel while reading sql results

src/main/mondrian/rolap/FastBatchingCellReader.java, src/main/mondrian/spi/Dialect.java, src/main/mondrian/spi/impl/JdbcDialectImpl.java, src/main/mondrian/spi/impl/VerticaDialect.java
=> [MONDRIAN-1977] Distinct Count Performance Improvement for Vertica

testsrc/main/mondrian/rolap/NativeFilterMatchingTest.java, testsrc/main/mondrian/rolap/TestAggregationManager.java, testsrc/main/mondrian/test/BasicQueryTest.java
@lucboudreau 
fixes recent failures with testCancelSqlFetch*, testNameExpressionSnowflake (oracle), testNativeFilterWithCompoundSlicer* (non-native)
=> [TEST] fix some regression-core tests

src/main/mondrian/udf/CurrentDateMemberUdf.java, testsrc/main/mondrian/udf/CurrentDateMemberUdfTest.java
@lucboudreau, could you review, please
=> SP-1662 - Backport of MONDRIAN-2256 to 3.9 branch

src/main/mondrian/rolap/sql/CrossJoinArgFactory.java, testsrc/main/mondrian/rolap/sql/CrossJoinArgFactoryTest.java, testsrc/main/mondrian/test/Main.java
@lucboudreau, would you mind review/merge
=> MONDRIAN-2287 - ClassCastException during native evaluation

src/main/mondrian/rolap/RolapMemberBase.java, testsrc/main/mondrian/olap/fun/UnionFunDefTest.java, testsrc/main/mondrian/test/Main.java
@lucboudreau, take a look, please
=> [MONDRIAN-2250] - Inconsistent results in MDX Query

src/main/mondrian/rolap/RolapMemberBase.java, testsrc/main/mondrian/olap/fun/UnionFunDefTest.java, testsrc/main/mondrian/test/Main.java
@lucboudreau,  @kurtwalker - here is backport for https://github.com/pentaho/mondrian/pull/443
=> SP-1724 - Backport of MONDRIAN-2250 to 3.9 branch

src/main/mondrian/spi/impl/SybaseDialect.java, testsrc/main/mondrian/spi/impl/SybaseDialectTest.java, testsrc/main/mondrian/test/Main.java
@lucboudreau, would you mind reviewing/merging
=> MONDRIAN-2259 - Sybase SQL Anywhere 16 - Incorrect syntax near 'DATE' shown in Analyzer

src/main/java/mondrian/util/Ord.java
attribution
What was done:
added license header
=> MONDRIAN-2252 -- Ord.java seems to have wrong / missing license

src/main/mondrian/olap4j/IMondrianOlap4jProperty.java, src/main/mondrian/olap4j/MondrianOlap4jCellSetAxisMetaData.java, src/main/mondrian/olap4j/MondrianOlap4jProperty.java, src/main/mondrian/xmla/XmlaHandler.java, testsrc/main/mondrian/test/Main.java, testsrc/main/mondrian/xmla/XmlaDimensionPropertiesTest.java, testsrc/main/mondrian/xmla/XmlaDimensionPropertiesTest.ref.xml
@lucboudreau, here is backport of https://github.com/pentaho/mondrian/pull/456
thanks
=> SP-1811 - BACKPORT of  MONDRIAN-2302 (3.9)

ivy.xml
other pentaho projects and to fix a test dependent on
1.9.x features.
=> [TEST] Updating mockito to 1.9.5 to be consistent with

src/main/mondrian/server/FileRepository.java, testsrc/main/mondrian/server/FileRepositoryTest.java
@lucboudreau, @kurtwalker 
here is cross link for https://github.com/pentaho/mondrian/pull/467
=> MONDRIAN-2238 - REGRESSION: XMLA servlet does not recognize the Datasource Name in its legacy form

src/main/mondrian/server/FileRepository.java, testsrc/main/mondrian/server/FileRepositoryTest.java
@lucboudreau, @kurtwalker here are changes according to Luck's patch
=> Backport of MONDRIAN-2338 - REGRESSION: XMLA servlet does not recognize the Datasource Name in its legacy form (5.3 Suite)

testsrc/main/mondrian/xmla/XmlaDimensionPropertiesTest.java, testsrc/main/mondrian/xmla/XmlaDimensionPropertiesTest.ref.xml
@kurtwalker, @lucboudreau here are changes strictly according to jira issue.
=> MONDRIAN-2302 - Revorked Tests.

testsrc/main/mondrian/xmla/XmlaDimensionPropertiesTest.java, testsrc/main/mondrian/xmla/XmlaDimensionPropertiesTest.ref.xml
@kurtwalker and here are changes for 3.9 branch,
thanks, Yury.
=> SP-1811 - Backport of MONDRIAN-2302 - Revorked Tests.

doc/vba_functions.html, src/main/mondrian/olap/fun/vba/Vba.java, testsrc/main/mondrian/olap/fun/vba/VbaTest.java
- change Interval.diff() for D and Y members to mimic DateDiff function from VBA
- add test cases for DateDiff('y'/'d',...)
- do some cosmetic changes to make affected class follow the checkstyle
@mkambol, @lucboudreau, review it please
=> [MONDRIAN-2319] - Calculating Date difference produce wrong result

src/main/mondrian/olap/fun/UdfResolver.java, testsrc/main/mondrian/rolap/FastBatchingCellReaderTest.java
@lucboudreau, @mkambol, would you mind of reviewing/merging
=> Mondrian-2251 - Exceeding CellBatchSize when evaluating a UDF causes an error

testsrc/main/mondrian/rolap/FastBatchingCellReaderTest.java
@mkambol, would you mind reviewing/merging it
=> [MONDRIAN-2251] - JUnit is reworked

src/main/mondrian/rolap/CacheControlImpl.java, src/main/mondrian/rolap/RolapNativeRegistry.java, src/main/mondrian/rolap/RolapNativeSet.java, testsrc/main/mondrian/rolap/CacheControlTest.java
@mkambol, @lucboudreau, take a look, please
=> MONDRIAN-2366 - CacheControl.flush(MemberSet) does not flush NativeSet member caches.

src/main/mondrian/rolap/RolapResult.java
@mkambol, it was my fault. Is repaired
=> [MONDRIAN-2361] - Reworked.

src/main/mondrian/olap/fun/CrossJoinFunDef.java
@mkambol, imports is cleaned. Merge it please. Thanks.
=> [MONDRIAN-2361] - cleanup imports

src/main/mondrian/olap/fun/CrossJoinFunDef.java, src/main/mondrian/olap/fun/FunUtil.java, src/main/mondrian/resource/MondrianResource.xml, src/main/mondrian/rolap/RolapConnection.java, src/main/mondrian/rolap/RolapCube.java, src/main/mondrian/rolap/RolapResult.java, src/main/mondrian/rolap/RolapSchema.java, src/main/mondrian/rolap/SqlMemberSource.java
@mkambol, here is backport of MONDRIAN-2361 to 3.10 ( just warning messages as was decided ).Thanks.
=> Backport of MONDRIAN-2361 - Using the highCardinality flag can cause incorrect results with Aggregates (5.4 Suite)

src/main/mondrian/olap/fun/FunUtil.java, src/main/mondrian/olap/fun/PercentileFunDef.java, testsrc/main/mondrian/olap/fun/FunctionTest.java
@mkambol, @lucboudreau, would you mind of reviewing/merging? - the major issue for https://github.com/pentaho/mondrian/pull/513
=> Mondrian 2343 - Percentile function does not calculate correctly

src/main/mondrian/olap/fun/FunUtil.java, src/main/mondrian/olap/fun/PercentileFunDef.java, testsrc/main/mondrian/olap/fun/FunctionTest.java
@mkambol, @lucboudreau, take a look, please. All changes have checked on compatibility with MS Excel. I have not sent PR to master branch yet.
=> 3.10.0 - Backport of MONDRIAN-2343 - Percentile function does not calculate correctly (5.4 Suite)

testsrc/main/mondrian/rolap/CacheControlTest.java, testsrc/main/mondrian/test/NativeSetEvaluationTest.java
1) Old JUnit test is removed.
2) New JUnit test is added.
@mkambol, accidentally I attached the test from jira. Here is the correct one.
=> [MONDRIAN-2366] - JUnit test. Reworked.

src/main/mondrian/rolap/RolapSchema.java, src/main/mondrian/rolap/RolapSchemaPool.java, testsrc/main/mondrian/rolap/RolapSchemaPoolConcurrencyTest.java, testsrc/main/mondrian/test/Main.java
@mkambol, @lucboudreau, review it please (actually, I suppose the JIRA case needs to be triaged first)
@julianhyde, I will highly appreciate if you also put your remarks
=> [MONDRIAN-2390] - Poor performance when accessing RolapSchemaPool from many threads

src/main/mondrian/olap/Util.java
- add the condition removed by eb29061f34263816cf35781cf2d689be6c0bd5ad
- apply proper formatting
@mkambol, @lucboudreau, review it please
=> [TEST] - recover a failing test

ivy.xml
!! Do not merge until we get the official go-ahead for VFS2.1.
=> Upgrading to VFS 2.1

src/main/mondrian/rolap/RolapNativeSql.java, testsrc/main/mondrian/rolap/RolapNativeTopCountTest.java, testsrc/main/mondrian/test/Main.java
- handle DefExpr missing: use "*" in such cases
- add tests for native TopCount function
- apply proper formatting for all affected classes
@mkambol, @lucboudreau, review it please.
=> [MONDRIAN-2322] - TopCount with Implicit Fact Count measure raises NullPointerException

src/main/mondrian/olap/fun/ValidMeasureFunDef.java, testsrc/main/mondrian/olap/fun/ValidMeasureFunDefTest.java, testsrc/main/mondrian/test/Main.java
@mkambol, @lucboudreau, would you mind if reviewing/merging
=> MONDRIAN-1032 - ValidMeasure only takes into account the first hierarchy of every dimension

src/main/mondrian/olap/fun/TopBottomPercentSumFunDef.java, testsrc/main/mondrian/olap/fun/FunctionTest.java
@mkambol, @lucboudreau, take a look, please
=> [MONDRIAN-2157] - TopPercent() get a NullPointerException

testsrc/main/mondrian/test/NativeSetEvaluationTest.java
=> [TEST]  correcting failed test that's dependent on non-agg SQL.

src/main/mondrian/olap/fun/ValidMeasureFunDef.java, testsrc/main/mondrian/olap/fun/ValidMeasureFunDefTest.java, testsrc/main/mondrian/test/Main.java
@mkambol, @lucboudreau, here is backport of https://github.com/pentaho/mondrian/pull/541.Thanks.
=> [SP-2131] - Backport of MONDRIAN-1032 - ValidMeasure only takes into account the first hierarchy of every dimension (5.4 Suite)

src/main/mondrian/olap/fun/TopBottomPercentSumFunDef.java, testsrc/main/mondrian/olap/fun/FunctionTest.java
[MONDRIAN-2157] - TopPercent() get a NullPointerException
=> [MONDRIAN-2157] - JUnit test

src/main/mondrian/gui/Workbench.java
One liner to include the "plugins" dir in the KETTLE_PLUGIN_BASE_FOLDERS list.
@lucboudreau @bmorrise @hudak
=> [BACKLOG-5370]  "Pentaho Data Services" database type not in list

build.xml
=> [CLEANUP]  Removing jdk15 compilation.  jdk16+ is required.

testsrc/main/mondrian/olap/fun/FunctionTest.java
@lucboudreau, @mkambol here is test thad shows that the issue is not reproduced. Thanks.
=> [MONDRIAN-1187] - JUnit test

src/main/mondrian/rolap/RolapNativeSql.java, testsrc/main/mondrian/rolap/NativeFilterAgainstAggTableTest.java, testsrc/main/mondrian/rolap/NativeFilterMatchingTest.java, testsrc/main/mondrian/test/Main.java
- use aggregation table's rollup aggregator instead of measure's
- add tests
@mkambol, @lucboudreau, review it please
=> [MONDRIAN-2155] - Invalid results when using native filter and topcount with aggregate table measures

src/main/mondrian/rolap/agg/SegmentBuilder.java, testsrc/main/mondrian/rolap/agg/SegmentBuilderTest.java
@mkambol, @lucboudreau, review it please.
=> [MONDRIAN-2406] - Boolean dimensions poison the cache

src/main/mondrian/rolap/RolapAggregationManager.java, testsrc/main/mondrian/test/DrillThroughFieldListTest.java, testsrc/main/mondrian/test/Main.java
@mkambol, @lucboudreau, could you please take a look?
=> [MONDRIAN-2383] - Extra joins in Mondrian generated query after selecting columns on drill-through option from Analyzer

src/main/mondrian/rolap/agg/SegmentBuilder.java, testsrc/main/mondrian/rolap/agg/SegmentBuilderTest.java
@mkambol, @lucboudreau, review it please. This is a backport of https://github.com/pentaho/mondrian/pull/584
=> [SP-2238] - Backport of MONDRIAN-2406 - Boolean dimensions poison the cache (6.0 Suite)

src/main/mondrian/rolap/agg/SegmentBuilder.java, testsrc/main/mondrian/rolap/agg/SegmentBuilderTest.java
@mkambol, @lucboudreau, review it please. This is a backport of https://github.com/pentaho/mondrian/pull/584
=> [SP-2239] - Backport of MONDRIAN-2406 - Boolean dimensions poison the cache (5.4 Suite)

src/main/mondrian/rolap/RolapAggregationManager.java, testsrc/main/mondrian/test/DrillThroughFieldListTest.java, testsrc/main/mondrian/test/Main.java
@mkambol, this is backport of MONDRIAN-2383 to 6.0.
Could you please take a look?
=> SP-2230 - Backport of MONDRIAN-2383 - Extra joins in Mondrian generated query after selecting columns on drill-through option from Analyzer

src/main/mondrian/rolap/DefaultTupleConstraint.java, src/main/mondrian/rolap/DescendantsConstraint.java, src/main/mondrian/rolap/MemberExcludeConstraint.java, src/main/mondrian/rolap/RolapNativeSet.java, src/main/mondrian/rolap/RolapNativeTopCount.java, src/main/mondrian/rolap/SqlConstraintUtils.java, src/main/mondrian/rolap/SqlContextConstraint.java, src/main/mondrian/rolap/SqlTupleReader.java, src/main/mondrian/rolap/sql/MemberKeyConstraint.java, src/main/mondrian/rolap/sql/TupleConstraint.java, testsrc/main/mondrian/rolap/RolapNativeTopCountTestCases.java, testsrc/main/mondrian/rolap/RolapNativeTopCountVersusNonNativeTest.java, testsrc/main/mondrian/rolap/TopCountNativeEvaluatorTest.java, testsrc/main/mondrian/rolap/TopCountWithTwoParamsVersusHeadTest.java, testsrc/main/mondrian/test/AccessControlTest.java, testsrc/main/mondrian/test/FoodMartTestCase.java, testsrc/main/mondrian/test/Main.java, testsrc/main/mondrian/test/NativeSetEvaluationTest.java
=> [MONDRIAN-1272][MONDRIAN-2394][MONDRIAN-2430] Backports to CUST205.

testsrc/main/mondrian/rolap/RolapNativeSql_NumberSqlCompiler_Test.java
- fix failing test
@mkambol, @lucboudreau, @kurtwalker, merge it please to fix the failing test
=> [MONDRIAN-2436] - SQL Injection through MDX Filter

src/main/mondrian/rolap/RolapSchema.java, testsrc/main/mondrian/rolap/RolapSchemaTest.java, testsrc/main/mondrian/rolap/agg/AggregationOnInvalidRoleTest.java, testsrc/main/mondrian/rolap/agg/AggregationOnInvalidRoleWhenNotIgnoringTest.java, testsrc/main/mondrian/rolap/agg/mondrian_2225.csv, testsrc/main/mondrian/rolap/sql/SqlQueryTest.java, testsrc/main/mondrian/test/FoodMartTestCase.java, testsrc/main/mondrian/test/Main.java, testsrc/main/mondrian/test/NamedSetTest.java, testsrc/main/mondrian/test/PropertyRestoringTestCase.java
- remove hierarchy restrictions if it contains no members and was initially defined with CUSTOM access
- introduce separate methods for each OlapElement to be used in granting routine
- add tests
@mkambol, @lucboudreau, review it please
=> [MONDRIAN-2225] - Using aggregations with data restrictions return error

testsrc/main/mondrian/olap/fun/CrossJoinTest.java, testsrc/main/mondrian/rolap/CancellationTest.java, testsrc/main/mondrian/test/Main.java
=> [MONDRIAN-2425]  Adding a test to validate cancellation checks.

src/main/mondrian/olap/fun/CrossJoinFunDef.java, src/main/mondrian/server/Execution.java, testsrc/main/mondrian/olap/fun/CrossJoinTest.java, testsrc/main/mondrian/rolap/CancellationTest.java, testsrc/main/mondrian/test/Main.java
@mkambol, could you please take a look? - here is backport of https://github.com/pentaho/mondrian/pull/598 with your test.
=> Backport of MONDRIAN-2425 - MDX will not stop at timeout for certain Analyzer reports with totals/subtotals (6.0 Suite)

bin/checkFile.awk
@mkambol, @lucboudreau, could you merge it please
=> [CLEANUP] - update year in checkFile.awk

testsrc/main/mondrian/test/DrillThroughTest.java
@lucboudreau, @mkambol, could you merge it please?
=> [TEST] - Add oracle dialect support to DrillThroughTest

testsrc/main/mondrian/test/DrillThroughFieldListTest.java
@lucboudreau, @mkambol, could you merge it please?
=> [TEST] - Add oracle dialect support to DrillThroughFieldListTest

testsrc/main/mondrian/rolap/agg/AggregationOnDistinctCountMeasuresTest.java
- change caught SQL expression: `"store"."store_country" = "USA" --> "store"."store_state" in ("CA", "OR", "WA")` in `testCanNotBatchForDifferentCompoundPredicate()`
- replace manual property restoring with `propSaver.set()` calls
- apply proper formatting
@mkambol, @lucboudreau, @kurtwalker, review it please.
The failing test was written in 2009. It does not pass in Oracle environment (http://ci.pentaho.com/view/Mondrian/job/mondrian-trunk-regression-tests-core/5368/testReport/). I checked and verified it also fails in 3.9, thus it is not a recent regression.
It passes on CI because it has no SQL expressions for MySQL. My debugging revealed the difference between what Mondrian actually generates and what the test expects:
```
select "time_by_day"."the_year" as "c0", count(distinct …
```
=> [TEST] - fix AggregationOnDistinctCountMeasuresTest

testsrc/main/mondrian/rolap/RolapNativeSqlInjectionTest.java
- explicitly set proper parameters to work in native mode
@mkambol, @lucboudreau, @kurtwalker, review it please
=> [TEST] - Make RolapNativeSqlInjectionTest tolerant to different environments

testsrc/main/mondrian/rolap/NativeFilterAgainstAggTableTest.java
- explicitly set proper parameters to enable native mode
@mkambol, @lucboudreau, @kurtwalker, review it please.
=> [TEST] - Make NativeFilterAgainstAggTableTest tolerant to different environments

testsrc/main/mondrian/rolap/aggmatcher/MultipleColsInTupleAggTest.java
@lucboudreau, @mkambol, could you merge it please?
=> [TEST] - Add oracle dialect support to MultipleColsInTupleAggTest

testsrc/main/mondrian/rolap/aggmatcher/NonCollapsedAggTest.java
@lucboudreau, @mkambol, could you merge it please?
=> [TEST] - Updating NonCollapsedAggTest to pass with disabled agg tables

testsrc/main/mondrian/rolap/sql/EffectiveMemberCacheTest.java, testsrc/main/mondrian/test/NativeSetEvaluationTest.java
=> [TEST]  Test fixes

testsrc/main/mondrian/rolap/CacheControlTest.ref.xml
=> [TEST]  Checksum in expecteds for non-native was not updated with commit 2f7948.

testsrc/main/mondrian/rolap/agg/AggregationOnInvalidRoleTest.java, testsrc/main/mondrian/rolap/agg/mondrian_2225.csv
- explicitly set proper parameters to work in native mode
- fix a typo: dim_Code -> dim_code in the scheme
@mkambol, @lucboudreau, @kurtwalker, review it please
=> [TEST] - Make AggregationOnInvalidRoleTest tolerant to different environments

src/main/mondrian/util/CancellationChecker.java
@mkambol, @lucboudreau, commit-repairing failed ITest: https://github.com/pentaho/mondrian/pull/639#issuecomment-176902277. Thanks.
CC @kurtwalker
=> [MONDRIAN-2279] - Added check for non-null

testsrc/main/mondrian/test/NativeSetEvaluationTest.java
=> [TEST]  testSlicerTuplesFullCrossJoin fails in non-native due to known bug.

testsrc/main/mondrian/rolap/aggmatcher/NonCollapsedAggTest.java
loaded fresh with current property values.
@lucboudreau @kurtwalker
=> [TEST]  Change to TestContext creation to assure schema

testsrc/main/mondrian/olap/fun/FunctionTest.java, testsrc/main/mondrian/test/BasicQueryTest.java, testsrc/main/mondrian/test/TestContext.java
@mkambol , @lucboudreau , could you review it , please
The solution touches tests only.
Anonymous class names are replaced with stubs before comparison.
Any other solution, I could find, touches the applcation code (e.g. Calc or CalcWriter).
=> Mondrian 2454

testsrc/main/mondrian/olap/fun/FunctionTest.java
=> [TEST] - timeout needs to be lower to get consistent failure

testsrc/main/mondrian/test/Olap4jTckTest.java
olap4jtck until expected values can be updated.
@lucboudreau @kurtwalker
=> [TEST]  Disabling the "false positive" failure in

src/main/mondrian/util/Bug.java, testsrc/main/mondrian/test/SteelWheelsSchemaTest.java
=> [TEST]  Disabling test associated with a logged bug when aggregates are enabled.

src/main/mondrian/resource/MondrianResource.xml, src/main/mondrian/rolap/CompoundPredicateInfo.java, src/main/mondrian/rolap/RolapAggregationManager.java, src/main/mondrian/rolap/RolapEvaluator.java, src/main/mondrian/rolap/SqlConstraintUtils.java, testsrc/main/mondrian/olap/fun/FunctionTest.java, testsrc/main/mondrian/rolap/SqlConstraintUtilsTest.java, testsrc/main/mondrian/test/CompoundSlicerTest.java, testsrc/main/mondrian/test/Main.java
@mkambol , could you review it, please?
I have a doubt about the line
https://github.com/pentaho/mondrian/compare/master...ivanpogodin:MONDRIAN-2438?expand=1#diff-1c1415254ae1023ca8f35b5f35499a21R369
This condition is made required but it might be checked instead.
=> Mondrian 2438

bin/checkFile.awk
@mkambol, @lucboudreau, could you merge it please
=> [CLEANUP] - update year in checkFile.awk (3.10 branch)

src/main/mondrian/olap/fun/CrossJoinFunDef.java, testsrc/main/mondrian/olap/fun/UnionFunDefTest.java
@mkambol could you please take a look?
=> Mondrian [2250] - additional fix

src/main/mondrian/rolap/CompoundPredicateInfo.java, src/main/mondrian/rolap/RolapNativeFilter.java, src/main/mondrian/rolap/SqlConstraintUtils.java, src/main/mondrian/rolap/SqlContextConstraint.java, src/main/mondrian/rolap/SqlMemberSource.java, src/main/mondrian/rolap/SqlTupleReader.java, src/main/mondrian/rolap/TupleConstraintStruct.java, testsrc/main/mondrian/rolap/SqlConstraintUtilsTest.java, testsrc/main/mondrian/test/TupleListTest.java
I added support for disjoint tuples as expanded element
@mkambol please review it
=> [MONDRIAN-2441] fixed calculated member set issue for multicolumn result

testsrc/main/mondrian/test/CompoundSlicerTest.java, testsrc/main/mondrian/test/TupleListTest.java
it's just moving tests from https://github.com/pentaho/mondrian/pull/672 to proper class
@kurtwalker please merge this
=> [MONDRIAN-2441] [TEST] tests were moved

src/main/mondrian/rolap/CompoundPredicateInfo.java, src/main/mondrian/rolap/RolapNativeFilter.java, src/main/mondrian/rolap/SqlConstraintUtils.java, src/main/mondrian/rolap/SqlContextConstraint.java, src/main/mondrian/rolap/SqlMemberSource.java, src/main/mondrian/rolap/SqlTupleReader.java, src/main/mondrian/rolap/TupleConstraintStruct.java, testsrc/main/mondrian/rolap/SqlConstraintUtilsTest.java, testsrc/main/mondrian/test/TupleListTest.java
packport of https://github.com/pentaho/mondrian/pull/672
=> [SP-2635] Backport of MONDRIAN-2441 - Compound aggregated member in the slicer causes incorrect results with native eval (6.1 Suite)

src/main/mondrian/rolap/RolapCube.java
@lucboudreau we need this one public for the analyzer util also.
@rfellows @kolinus
=> [BACKLOG-5895] - making getFact public on RolapCube

src/main/mondrian/rolap/RolapSchema.java, src/main/mondrian/rolap/RolapSchemaPool.java, testsrc/main/mondrian/rolap/RolapSchemaPoolConcurrencyTest.java, testsrc/main/mondrian/rolap/RolapSchemaTest.java, testsrc/main/mondrian/test/Main.java
@mkambol, @kurtwalker, @lucboudreau, could you please take a look?
=> [SP-2663] - Backport of MONDRIAN-2390 - Poor performance when accessing RolapSchemaPool from many threads (5.4 Suite)

src/main/mondrian/rolap/RestrictedMemberReader.java, testsrc/main/mondrian/test/SteelWheelsAggregationTest.java
[MONDRIAN-2440] Error when using aggregation tables with a hierarchy that has a visible level behind restricted - fix and refactor
=> [MONDRIAN-2440] Error when using aggregation tables with a hierarchy that has a visible level behind restricted

src/main/mondrian/rolap/agg/SegmentBuilder.java, testsrc/main/mondrian/rolap/agg/SegmentBuilderTest.java
=> [MONDRIAN-2462] arrayIndexOutOfBounds encountered when performing rollup

src/main/mondrian/rolap/agg/SegmentBuilder.java, testsrc/main/mondrian/rolap/agg/SegmentBuilderTest.java
backport of MONDRIAN-2462
picked from https://github.com/pentaho/mondrian/pull/692
@lucboudreau please merge
=> [SP-2691] ArrayIndexOutOfBounds encountered when performing rollup

src/main/mondrian/rolap/agg/SegmentBuilder.java, testsrc/main/mondrian/rolap/agg/SegmentBuilderTest.java
backport of MONDRIAN-2462
picked from #692
@lucboudreau @mkambol @pamval  please merge
=> [SP-2692] ArrayIndexOutOfBounds encountered when performing rollup

src/main/mondrian/rolap/RolapCell.java, testsrc/main/mondrian/test/DrillThroughExcludeFilterTest.java, testsrc/main/mondrian/test/Main.java
Add method to identify appropriate base cube in order to get correct star key column.
=> [ANALYZER-3256] - NullPointerException when using Virtual Cube Drillthrough with exclude filter on level not present in report

src/main/mondrian/olap/fun/BuiltinFunTable.java, src/main/mondrian/olap/fun/ExistingFunDef.java, src/main/mondrian/olap/fun/ExistsFunDef.java, src/main/mondrian/olap/fun/FunUtil.java, src/main/mondrian/parser/MdxParser.jj, testsrc/main/mondrian/olap/fun/FunctionTest.java
@mkambol @lucboudreau please review
=> [MONDRIAN-1180] Support EXISTING keyword

src/main/mondrian/rolap/RolapConnection.java, testsrc/main/mondrian/rolap/RolapConnectionTest.java
=> [MONDRIAN-2511] Removed logged jdbc password

src/main/mondrian/olap/fun/ExistingFunDef.java, src/main/mondrian/olap/fun/ExistsFunDef.java, src/main/mondrian/olap/fun/FunUtil.java, testsrc/main/mondrian/olap/fun/FunctionTest.java
@lucboudreau @mkambol please review
=> [MONDRIAN-1180] always use current context in existing

src/main/mondrian/olap/fun/vba/Vba.java, testsrc/main/mondrian/olap/fun/vba/VbaTest.java
=> [MONDRIAN-2147] VBA Cdbl(String) losing decimal part

src/main/mondrian/tui/XmlUtil.java, src/main/mondrian/util/XmlParserFactoryProducer.java, src/main/mondrian/xmla/XmlaConstants.java, src/main/mondrian/xmla/XmlaUtil.java, src/main/mondrian/xmla/impl/DefaultXmlaServlet.java
@mkambol, @mbatchelor, could please take a look?  
Also, I'm not sure if we should do the same chabges here: https://github.com/pentaho/mondrian/blob/53295633f56fd13290169e3271bbab489ef4e3a6/src/main/mondrian/xmla/impl/DefaultXmlaServlet.java#L68 (is XXE possible there)? Thanks.
=> [PPP-3506] - XXE Security Vulnerability in xml parsers

src/main/mondrian/olap/fun/vba/Vba.java, testsrc/main/mondrian/olap/fun/vba/VbaTest.java
=> [SP-2984] Backport of MONDRIAN-2147 - VBA Cdbl(String) losing decimal part (6.1 Suite)

src/main/mondrian/rolap/RolapResult.java, src/main/mondrian/server/Execution.java
=> [MONDRIAN-1449] Monitor counters for cache hits and other metrics canbe incorrect

assemblies/psw-ce/pom.xml, pom.xml
=> [CLEANUP] add profiles to module activation & remove assemblyId from psw-ce

ivy.xml
=> Revert "[PPP-3506] - XXE Security Vulnerability in xml parsers"

src/main/mondrian/rolap/RolapResult.java, src/main/mondrian/server/Execution.java
=> [SP-3009] Backport of MONDRIAN-1449 - Monitor counters for cache hits and other metrics can be incorrect (6.1 Suite)

src/main/mondrian/rolap/RolapResult.java, src/main/mondrian/server/Execution.java
=> [SP-3008] Backport of MONDRIAN-1449 - Monitor counters for cache hits and other metrics can be incorrect (7.0 Suite)

mondrian/src/it/java/mondrian/test/BasicQueryTest.java, mondrian/src/main/java/mondrian/rolap/RolapCube.java
If primaryKeyTable do not references to the leftmost table, then we swap it.
=> [MONDRIAN-2245] Mondrian omits primaryKeyTable if it is the right table of a Join

mondrian/src/it/java/mondrian/rolap/CacheControlTest.java, mondrian/src/it/java/mondrian/rolap/CacheControlTest.ref.xml, mondrian/src/it/java/mondrian/rolap/agg/SegmentBuilderTest.java, mondrian/src/it/java/mondrian/test/DiffRepository.java
JDK dependent tests were updated - now JDK version doesn't cause any headache;
Some tests were result order dependent despite it wasn't necessary - it caused another OS/JDK dependency.
=> [TEST] Failing tests

mondrian/src/it/java/mondrian/rolap/NonEmptyTest.java, mondrian/src/main/java/mondrian/olap/fun/CrossJoinFunDef.java
=> [MONDRIAN-328] CrossJoin non empty optimizer eliminates calculated member

mondrian/src/it/resources/mondrian/test/loader/SteelWheels.mysql.sql, mondrian/src/it/resources/sql/create-foodmart.sql
Locally full IT suite went from 14 mins to 8:42.  woohoo.
=> [TEST] - changing embedded mysql database to use memory storage engine

mondrian/src/it/java/mondrian/rolap/NonEmptyTest.java, mondrian/src/it/java/mondrian/test/BasicQueryTest.java, mondrian/src/main/java/mondrian/olap/fun/DescendantsFunDef.java
Descendants function is NON EMPTY dependent now.
=> [MONDRIAN-625] The Descendants function will only return Non Empty member children, even if it is not specified inside of NON EMPTY

src/main/mondrian/olap/fun/CrossJoinFunDef.java, testsrc/main/mondrian/rolap/NonEmptyTest.java
=> [SP-3337] Backport of MONDRIAN-328 - CrossJoin non empty optimizer eliminates calculated member (7.0 Suite)

testsrc/main/mondrian/rolap/NativeEvalVirtualCubeTest.java
=> [TEST]Failing test

mondrian/src/it/java/mondrian/rolap/NonEmptyTest.java, mondrian/src/it/java/mondrian/test/NativeSetEvaluationTest.java, mondrian/src/main/java/mondrian/rolap/SqlContextConstraint.java
=> [MONDRIAN-2138] Incorrect results when non-all defaultMember is used with .children in NON EMPTY context

mondrian/src/it/java/mondrian/test/SchemaTest.java, mondrian/src/main/java/mondrian/rolap/RolapCubeDimension.java, mondrian/src/main/java/mondrian/rolap/RolapDimension.java
- fixed mistakes in constructors
- fixed incorrect behaviour with setting description in RolapCubeDimension constructor
- added test
=> [MONDRIAN-1275] Annotations seem to disappear in shared dimensions

mondrian/src/it/java/mondrian/util/FormatTest.java, mondrian/src/main/java/mondrian/util/Format.java
@DFieldFL @kurtwalker 
Please review.
=> [BACKLOG-15504] - DET - Model View - we are seeing semicolon in values

mondrian/src/it/java/mondrian/test/NamedSetTest.java, mondrian/src/main/java/mondrian/olap/IdBatchResolver.java
- lookupExp was changed - named set incorrect identification was fixed
=> [MONDRIAN-2424] Query defining set or member does not work

mondrian/src/it/java/mondrian/rolap/RolapDimensionTest.java, mondrian/src/main/java/mondrian/rolap/RolapDimension.java, mondrian/src/main/java/mondrian/rolap/RolapHierarchy.java
- get rid of implicit MondrianDef.Hierarchy.relation set to cube.fact
=> [PAD-159] Aggregate attributes are added to degenerate dimensions

assemblies/psw-ce/pom.xml, workbench/pom.xml
@lgrill-pentaho Please review. Tested change with the following jobs:
http://cerberusdmz.pentaho.com/job/7.1/job/mondrian-jar/192/consoleFull
http://cerberusdmz.pentaho.com/job/7.1/job/mondrian-workbench/182/consoleFull
http://cerberusdmz.pentaho.com/job/7.1/job/psw-assembly/185/consoleFull
=> [CLEANUP] Update application launcher version property

mondrian/src/it/java/mondrian/test/DialectTest.java, mondrian/src/main/java/mondrian/spi/impl/VectorwiseDialect.java
@mbatchelor, @lucboudreau, could you please take a look?
=> [MONDRIAN-2253] - Pentaho analyzer is throwing error when multiple shared dimensions are used in a virtual cube - Vectorwise DB

mondrian/src/main/java/mondrian/olap/Mondrian.xml, mondrian/src/main/resources/mondrian.xsd, workbench/src/main/java/mondrian/olap/Mondrian_SW.xml
- unsupported datatypes were removed
=> [PSW-230] PSW Allows you to select Measures' datatypes that are not supported

assemblies/psw-ce/src/main/resources/cpappend.bat, assemblies/psw-ce/src/main/resources/set-pentaho-env.bat, assemblies/psw-ce/src/main/resources/set-pentaho-env.sh, assemblies/psw-ce/src/main/resources/workbench.bat, assemblies/psw-ce/src/main/resources/workbench.sh, bin/checkFile.sh, bin/loadFoodMart.sh, bin/run.sh, bin/runtest.sh, mondrian/src/site/resources/doc/deployDoc.sh, mondrian/src/site/resources/doc/doc2web.sh
=> [PSW-229] Script files don't have an header with Copyright data

mondrian/src/main/java/mondrian/olap/Mondrian.xml, mondrian/src/main/resources/mondrian.xsd, workbench/src/main/java/mondrian/olap/Mondrian_SW.xml
=> [SP-3619] Backport of PSW-230 - PSW Allows you to select Measures' datatypes that are not supported (7.1 Suite)

mondrian/src/it/java/mondrian/test/BasicQueryTest.java
Fixed failed on master unit tests: http://10.177.176.33:8081/view/MONDRIAN/job/mondrian_314_maven/lastBuild/testReport/
It seems that unit tests failures were introduced by commit: https://github.com/pentaho/mondrian/commit/0a22a971cd7d72d69ddf6d3b2b36bd04b0a52a16.
Fixed.
=> [CLEANUP]: Fixed unit tests failed on master 

.gitignore
Added the several ignores for Eclipse IDE.
=> [CLEANUP]: Added the several ignores for Eclipse IDE

mondrian/src/it/java/mondrian/xmla/XmlaBasicTest.java, mondrian/src/it/java/mondrian/xmla/XmlaBasicTest.ref.xml, mondrian/src/main/java/mondrian/olap/type/TypeUtil.java
Used the origin commit: https://github.com/pentaho/mondrian/pull/256/commits/10f4a562985cdc467e14c24a6199c30194baeb47
Changed the unit test to get exactly described in the issue NPE.
=> [MONDRIAN-2379]: Axes with empty sets cause NPE in XmlaHandler.

mondrian/src/it/java/mondrian/test/DiffRepository.java
- cache test specific logic was separated
=> [BACKLOG-18158] Some tests are always passed

pom.xml
@pentaho/rogueone @pentaho/rebelalliance @mkambol 
Driver version upgrade. please review.
=> [BACKLOG-17345] Upgrade Postgres JDBC Driver version to 42.1.1

mondrian/pom.xml
@lgrill-pentaho 
fixes IT failures associated with a hard-coded version test
=> [BACKLOG-18047] set major/minor props back to 3/150 to support ITs

mondrian/src/it/java/mondrian/spi/impl/MonetDbDialectTest.java, mondrian/src/it/java/mondrian/test/Main.java, mondrian/src/main/java/mondrian/spi/impl/MonetDbDialect.java
Added support distinct count for MonetDB dialect, added unit tests.
=> [MONDRIAN-2110]: Distinct Count measures not functional utilizing MonetDB

mondrian/src/it/java/mondrian/rolap/SqlMemberSourceTest.java, mondrian/src/it/java/mondrian/test/Main.java, mondrian/src/main/java/mondrian/rolap/SqlMemberSource.java
Applied the fix from the commit f4a3d9269466a1d93c08f7abe9e27bf348ee02e2, added the unit test.
=> [MONDRIAN-2595]: Count distinct Bug in SQLMemberSource

mondrian/src/it/java/mondrian/test/AccessControlTest.java, mondrian/src/main/java/mondrian/olap/RoleImpl.java
Fixed. Added unit test to cover changes.
=> [MONDRIAN-2586]: Ragged dimension members are not visible when using a single role

mondrian/src/main/java/mondrian/olap/Mondrian.xml, mondrian/src/main/java/mondrian/spi/Dialect.java, mondrian/src/main/java/mondrian/spi/impl/JdbcDialectImpl.java, mondrian/src/main/java/mondrian/spi/impl/PdiDataServiceDialect.java, mondrian/src/main/resources/META-INF/services/mondrian.spi.Dialect, workbench/src/main/java/mondrian/olap/Mondrian_SW.xml
Divided into 2 commits in order not to confuse pr changes with checkstyle
=> [PDI-16624]-Big Number fields are not correctly aggregated in DET. Added a new PdiDataServiceDialect

mondrian/src/it/java/mondrian/rolap/SqlMemberSourceTest.java, mondrian/src/it/java/mondrian/test/Main.java, mondrian/src/main/java/mondrian/rolap/SqlMemberSource.java
Cherry-picked commit for [MONDRIAN-2595]: Count distinct Bug in SQLMemberSource
=> [SP-3811]: Backport of MONDRIAN-2595 - Count distinct Bug in SQLMemberSource (7.1 Suite)

mondrian/src/it/java/mondrian/olap/fun/CrossJoinTest.java, mondrian/src/it/java/mondrian/test/Main.java, mondrian/src/it/java/mondrian/test/TupleListTest.java, mondrian/src/it/java/mondrian/util/CancellationCheckerTest.java, mondrian/src/main/java/mondrian/olap/fun/CrossJoinFunDef.java, mondrian/src/main/java/mondrian/olap4j/MondrianOlap4jCellSetAxis.java, mondrian/src/main/java/mondrian/util/CancellationChecker.java
Fixed according to the comment in the jira, added unit tests.
=> [MONDRIAN-2534]: Mondrian CancellationChecker.checkCancelOrTimeout does not terminate thread

mondrian/src/it/java/mondrian/test/DrillThroughTest.java, mondrian/src/main/java/mondrian/rolap/agg/DrillThroughQuerySpec.java
There are fix, integration test and fixes for check-style problems.
=> [MONDRIAN-2551]: Drill-through filtering not working properly when level is used as filter.

mondrian/src/it/java/mondrian/rolap/RolapSchemaTest.java, mondrian/src/it/java/mondrian/rolap/RolapUtilTest.java, mondrian/src/it/java/mondrian/test/Main.java, mondrian/src/it/java/mondrian/test/SchemaTest.java, mondrian/src/main/java/mondrian/rolap/RolapSchema.java, mondrian/src/main/java/mondrian/rolap/RolapUtil.java, mondrian/src/main/java/mondrian/rolap/agg/AggregationManager.java
There are fix, unit tests and the integration test.
=> [MONDRIAN-1073]: Two cubes operating on same fact table gives wrong WHERE clause

assemblies/psw-ce/pom.xml, workbench/pom.xml
WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!
=> [ENGOPS-1757] version name consolidation

mondrian/src/it/java/mondrian/spi/impl/JdbcDialectImplTest.java, mondrian/src/it/java/mondrian/spi/impl/MicrosoftSqlServerDialectTest.java, mondrian/src/main/java/mondrian/spi/impl/MicrosoftSqlServerDialect.java, mondrian/src/main/java/mondrian/spi/impl/MySqlDialect.java
Fixed, added unit tests, fixed check-style issues.
=> [MONDRIAN-1233]: MySQL/MS SQL Dialect needs to override Dialect.quoteBooleanLiteral

mondrian/src/it/java/mondrian/test/BasicQueryTest.java, mondrian/src/main/java/mondrian/rolap/RolapCubeHierarchy.java, mondrian/src/main/java/mondrian/rolap/RolapLevel.java, mondrian/src/main/java/mondrian/rolap/RolapMemberBase.java
There are fix, IT test and check-style fixes.
=> [MONDRIAN-2608]: Error with cached data when ordinalColumn is defined and parameter mondrian.native.ExpandNonNative is set to true

mondrian/src/it/java/mondrian/olap/fun/FunctionTest.java, mondrian/src/main/java/mondrian/olap/fun/BuiltinFunTable.java
=> [MONDRIAN-2610] - Error with UCase function

workbench/src/main/resources/mondrian/gui/resources/schemaBuilder.html
@lgrill-pentaho @emartin-pentaho
=> [PPP-3983] change splash screen from Pentaho to HV

assemblies/psw-ce/pom.xml, workbench/pom.xml
@pentaho/2-1b
Depends on https://github.com/pentaho/pentaho-commons-xul/pull/143
=> [BACKLOG-20423] Update downstreams

mondrian/src/it/java/mondrian/util/FormatTest.java, mondrian/src/main/java/mondrian/rolap/agg/SegmentLoader.java, mondrian/src/main/java/mondrian/util/Format.java
added correct processing BigDecimal without losing precision
=> [SP-4070][PDI-16761] In Model View, integer type numerical value more than 17 digits is rounded off

mondrian/src/it/java/mondrian/util/FormatTest.java, mondrian/src/main/java/mondrian/rolap/agg/SegmentLoader.java, mondrian/src/main/java/mondrian/util/Format.java
added correct processing BigDecimal without losing precision
=> [SP-4069][PDI-16761] In Model View, integer type numerical value more than 17 digits is rounded off

mondrian/src/it/java/mondrian/rolap/RolapStarTest.java, mondrian/src/it/java/mondrian/rolap/agg/GroupingSetsListTest.java, mondrian/src/it/java/mondrian/test/Main.java, mondrian/src/main/java/mondrian/rolap/RolapStar.java
There are fix, unit tests and a couple of checkstyle fixes.
=> [MONDRIAN-2604]: java.lang.ArrayIndexOutOfBoundsException while applying Filters

mondrian/src/it/java/mondrian/util/FormatTest.java, mondrian/src/main/java/mondrian/util/Format.java
=> [MONDRIAN-2613]: ArrayIndexOutOfBoundsException in mondrian.util.Format.formatFd2 formatting a BigDecimal

mondrian/src/it/java/mondrian/rolap/RolapStarTest.java, mondrian/src/it/java/mondrian/rolap/agg/GroupingSetsListTest.java, mondrian/src/it/java/mondrian/test/Main.java, mondrian/src/main/java/mondrian/rolap/RolapStar.java
This is the cherry-pick of the fix for [MONDRIAN-2604]: java.lang.ArrayIndexOutOfBoundsException while applying Filters
=> [SP-4133]: Backport of MONDRIAN-2604 - java.lang.ArrayIndexOutOfBoundsException while applying Filters. (8.0 Suite)

mondrian/src/main/java/mondrian/rolap/RolapStar.java
This is the back port of the fix for MONDRIAN-2604.
=> [SP-4132]: Backport of MONDRIAN-2604 - java.lang.ArrayIndexOutOfBoundsException while applying Filters. (7.1 Suite)

assemblies/psw-ce/pom.xml
@pentaho/x-wing, @lucboudreau  please review
=> [BACKLOG-22387] - PSW - Regression in assembly

workbench/src/main/resources/mondrian/gui/resources/schemaBuilder.html
=> [PSW-262] Copyright info on Schema workbench not okay

assemblies/psw-ce/pom.xml, mondrian/pom.xml, pom.xml
This is one of a series of PRs. See https://github.com/pentaho/maven-parent-poms/pull/70 for the complete list and more details. **Do not merge until further notice!**
@graimundo
=> [PPP-4182] Use of vulnerable component dom4j-1.6.1.jar  CVE-2018-1000632

mondrian/src/it/java/mondrian/olap/fun/FunctionTest.java, mondrian/src/it/java/mondrian/test/BasicQueryTest.java, mondrian/src/main/java/mondrian/olap/fun/IsNullFunDef.java
IS NULL checks were excluding members assigned a null key due
to missing data in the dim table.  SSAS treats these as null
members.
https://jira.pentaho.com/browse/MONDRIAN-2643
=> [MONDRIAN-2643] IS NULL checks incorrect against some null members

mondrian/pom.xml
=> [BACKLOG-26968] Update copyright versions to 2019

mondrian/pom.xml
=> [SP-4856] Backport of BACKLOG-26968 - Update copyright versions to 2019

mondrian/pom.xml
=> [SP-4857] Backport of BACKLOG-26968 - Update copyright versions to 2019

workbench/src/main/java/mondrian/gui/JdbcMetaData.java
=> [SP-5220] - Backport of BACKLOG-29977 - Schema Workbench is unusably slow when connected to Snowflake (8.3 Suite)

mondrian/src/it/java/mondrian/rolap/RolapConnectionTest.java, mondrian/src/main/java/mondrian/rolap/RolapConnection.java, mondrian/src/main/java/mondrian/rolap/RolapConnectionProperties.java
@pentaho/tatooine @pentaho-lmartins
=> [PAD-147] - Cannot connect to Mondrian with SQL Server datasource using Integrated Security

mondrian/src/main/java/mondrian/rolap/RolapSchemaPool.java
@LeonardoCoelho71950 
@lucboudreau 
@pentaho-lmartins 
@pentaho/tatooine
=> [ANALYZER-3828] - Saving an inline model breaks localization

mondrian/src/main/java/mondrian/spi/impl/JdbcDialectImpl.java
=> [MONDRIAN-2637] Sybase database not recognized

mondrian/src/it/java/mondrian/util/PartiallyOrderedSetTest.java, mondrian/src/main/java/mondrian/util/PartiallyOrderedSet.java
@lucboudreau @mkambol @kurtwalker 
This is only reproducible if we have assertions disabled, otherwise will fail here: https://github.com/pentaho/mondrian/blob/d08ca9a0dfc2dff949b2dea083441320b3a4f2af/mondrian/src/main/java/mondrian/util/PartiallyOrderedSet.java#L170
=> [MONDRIAN-2628] Possible race condition in PartiallyOrderedSet

mondrian/src/main/java/mondrian/spi/impl/JdbcDialectImpl.java
Merge Masters: @pentaho-lmartins and @smmribeiro
Cherry-picks:
* https://github.com/Pentaho/mondrian/commit/d46e6ac8a9bbdf3a084e6b32f998d8aee081e119
=> [SP-5322] Backport of MONDRIAN-2637 - Sybase database not recognized (8.3 Suite)

mondrian/src/it/java/mondrian/olap/fun/CachedExistsTest.java, mondrian/src/main/java/mondrian/olap/fun/extra/CachedExistsFunDef.java
Merge Masters: @pentaho-lmartins  and @smmribeiro
Cherry-picks:
* https://github.com/Pentaho/mondrian/commit/254dea9803db6daf68825375530d55f934c42637
=> [SP-5328] Backport of ANALYZER-3901 - TopN broken when fields are added to Columns (8.3 Suite)

mondrian/src/main/java/mondrian/olap/Mondrian.xml
@pentaho-lmartins @LeonardoCoelho71950 @kurtwalker
=> [PSW-269] - another Netezza typo

mondrian/src/main/java/mondrian/olap/Mondrian.xml, workbench/src/main/java/mondrian/olap/Mondrian_SW.xml
Merge Masters: @pentaho-lmartins and @smmribeiro
Cherry-picks:
* https://github.com/Pentaho/mondrian/commit/ba0daf210a396c84791b368321392c1cee4eb162
* https://github.com/Pentaho/mondrian/commit/ec124f72246d11cbd523b4a6140ec289eeafa860
* https://github.com/pentaho/mondrian/commit/0bfb950a17387586f074ba1c635cf68989e16ef2
=> [SP-5309] Backport of PSW-269 - Multiple dialects are missing from lists used in expressions (8.3 Suite)

mondrian/pom.xml, pom.xml
This reverts commit 85a100dfa2c5b2202c773703d270c98bb6abaf07, reversing
changes made to 0be05480e82b2f65e38f8fd8a774960738f08e39.
This Revert PR is part of a series:
- https://github.com/pentaho/maven-parent-poms/pull/229
- https://github.com/pentaho/apache-vfs-browser/pull/62
- https://github.com/pentaho/big-data-plugin/pull/2040
- https://github.com/webdetails/cpk/pull/87
- https://github.com/pentaho/data-access/pull/1091
- https://github.com/pentaho/mondrian/pull/1202
- https://github.com/pentaho/pdi-jms-plugin/pull/76
- https://github.com/pentaho/pdi-platform-utils-plugin/pull/104
- https://github.com/pentaho/pdi-plugins-ee/pull/174
- https://github.com/pentaho/pdi-sap-hana-bulk-loader-plugin/pull/84
- https://github.com/pentaho/pdi-teradata-tpt-plugin/pull/53
- …
=> Revert "Merge pull request #1197 from gryphendowre/SP-5370"

mondrian/src/it/java/mondrian/olap/fun/FunctionTest.java, mondrian/src/it/java/mondrian/olap/fun/TestMember.java, mondrian/src/main/java/mondrian/olap/Member.java, mondrian/src/main/java/mondrian/olap/MemberBase.java, mondrian/src/main/java/mondrian/olap/fun/FunUtil.java, mondrian/src/main/java/mondrian/rolap/DelegatingRolapMember.java, mondrian/src/main/java/mondrian/rolap/RolapResult.java
determine if it sits on the same hierarchy chain as another member.
=> [MONDRIAN-2664] Update Member to allow it to

mondrian/src/it/java/mondrian/olap/fun/FunctionTest.java, mondrian/src/it/java/mondrian/olap/fun/TestMember.java, mondrian/src/main/java/mondrian/olap/Member.java, mondrian/src/main/java/mondrian/olap/MemberBase.java, mondrian/src/main/java/mondrian/olap/fun/FunUtil.java, mondrian/src/main/java/mondrian/rolap/DelegatingRolapMember.java, mondrian/src/main/java/mondrian/rolap/RolapResult.java
=> Revert "[MONDRIAN-2664] Update Member to allow it to"

mondrian/src/it/java/mondrian/olap/fun/FunctionTest.java, mondrian/src/it/java/mondrian/olap/fun/TestMember.java, mondrian/src/main/java/mondrian/olap/Member.java, mondrian/src/main/java/mondrian/olap/MemberBase.java, mondrian/src/main/java/mondrian/olap/fun/FunUtil.java, mondrian/src/main/java/mondrian/rolap/RolapResult.java
Reverts pentaho/mondrian#1207
Commits were squashed which leads to difficulty backporting fix to previous baselines.
=> Revert "Mondrian 2664 redux"

mondrian/src/it/java/mondrian/olap/fun/FunctionTest.java, mondrian/src/it/java/mondrian/olap/fun/TestMember.java, mondrian/src/main/java/mondrian/olap/Member.java, mondrian/src/main/java/mondrian/olap/MemberBase.java, mondrian/src/main/java/mondrian/olap/fun/FunUtil.java, mondrian/src/main/java/mondrian/rolap/RolapResult.java
be handled correctly in EXISTING function calculations.
=> [MONDRIAN-2664] Update CompoundSlicerRolapMember in order to allow it to

mondrian/src/it/java/mondrian/test/DialectTest.java, mondrian/src/main/java/mondrian/resource/MondrianResource.xml, mondrian/src/main/java/mondrian/rolap/SqlStatement.java, mondrian/src/main/java/mondrian/spi/impl/SnowflakeDialect.java
work-around for loss of precision in getDouble method.
=> [MONDRIAN-2692] Get non-integer data from snowflake as a BigDecimal;

mondrian/src/main/java/mondrian/rolap/agg/SegmentLoader.java, mondrian/src/main/java/mondrian/spi/impl/SnowflakeDialect.java
=> [MONDRIAN-2692] Additional changes to work around snowflake getDouble

mondrian/pom.xml
=> [CUST-243] Updating versions for CUST case

mondrian/src/it/java/mondrian/test/BasicQueryTest.java, mondrian/src/main/java/mondrian/calc/CalcWriter.java, mondrian/src/main/java/mondrian/calc/impl/AbstractCalc.java, mondrian/src/main/java/mondrian/olap/Query.java, mondrian/src/main/java/mondrian/olap/QueryTiming.java, mondrian/src/main/java/mondrian/olap/fun/AvgFunDef.java, mondrian/src/main/java/mondrian/olap/fun/CountFunDef.java, mondrian/src/main/java/mondrian/olap/fun/MinMaxFunDef.java, mondrian/src/main/java/mondrian/olap/fun/OrderFunDef.java, mondrian/src/main/java/mondrian/olap/fun/PeriodsToDateFunDef.java, mondrian/src/main/java/mondrian/olap/fun/RankFunDef.java, mondrian/src/main/java/mondrian/olap/fun/SumFunDef.java, mondrian/src/main/java/mondrian/olap/fun/XtdFunDef.java, mondrian/src/main/java/mondrian/olap/fun/extra/CachedExistsFunDef.java, mondrian/src/main/java/mondrian/rolap/RolapNamedSetEvaluator.java, mondrian/src/main/java/mondrian/rolap/RolapResult.java, mondrian/src/main/java/mondrian/server/Execution.java
[MONDRIAN-2085] Query internal timing should be enabled only when required.
=> [MONDRIAN-2684] Improve Mondrian explain plan and timing features

workbench/src/main/java/mondrian/gui/SchemaExplorer.java
@ssamora 
@smmribeiro 
@moraesvc
=> [PSW-274] - Schema Workbench: Cannot add levels to hierarchy if only using a fact table - work-around described below

mondrian/src/it/java/mondrian/rolap/RolapEvaluatorTest.java, mondrian/src/it/java/mondrian/test/Main.java, mondrian/src/main/java/mondrian/olap/DriverManager.java, mondrian/src/main/java/mondrian/rolap/CompoundPredicateInfo.java
[MONDRIAN-2719] Performance issues when Mondrian is dealing with large slicer
[MONDRIAN-2721] Incorrect counters in MondrianMonitor
=> Fixes for MONDRIAN-2719 and MONDRIAN-2721

assemblies/psw-ce/pom.xml, assemblies/psw-ce/src/main/resources/log4j2.xml, mondrian/src/it/resources/log4j2.xml
=> Revert "[BISERVER-14720] Add log4j-jcl dependency"

assemblies/psw-ce/pom.xml, assemblies/psw-ce/src/main/resources/log4j2.xml, mondrian/src/it/resources/log4j2.xml
This commit is a cherry-pick from master 63fcdd6c7
=> [SP-6106] [BISERVER-14720] Add log4j-jcl dependency

assemblies/psw-ce/pom.xml, assemblies/psw-ce/src/main/resources/log4j2.xml, mondrian/src/it/resources/log4j2.xml
This commit is a cherry-pick from master 63fcdd6c7
=> [SP-6107] [BISERVER-14720] Add log4j-jcl dependency

pom.xml
This commit is a cherry-pick from master 0daf92f79
=> [SP-6179][PPP-4654] Get commons-io version from parent pom

assemblies/psw-ce/pom.xml
@smmribeiro 
@andreramos89 
@renato-s
=> [PPP-3713] - Beanshell version we're using is vulnerable to serialization exploit - CVE-2016-2510

mondrian/src/main/java/mondrian/rolap/MemberCacheHelper.java, mondrian/src/main/java/mondrian/rolap/RolapMember.java, mondrian/src/main/java/mondrian/rolap/SqlStatement.java
=> [SP-6337] - Backport of MONDRIAN-2733 - Performance issues when Mondrian is dealing with large GetMemberChildren queue (9.3 Suite)

mondrian/src/main/java/mondrian/olap/IdBatchResolver.java
@bcostahitachivantara @renato-s @andreramos89
=> [SP-6337] Backport of MONDRIAN-2733 - Performance issues when Mondrian is dealing with large GetMemberChildren queue (9.3 Suite)

mondrian/src/main/java/mondrian/olap/IdBatchResolver.java
@bcostahitachivantara @renato-s @andreramos89
=> [MONDRIAN-2733] Performance issues when Mondrian is dealing with large GetMemberChildren queue

mondrian/src/main/java/mondrian/olap/Query.java, mondrian/src/main/java/mondrian/olap/SchemaReader.java, mondrian/src/main/java/mondrian/olap/fun/AggregateFunDef.java, mondrian/src/main/java/mondrian/rolap/CacheMemberReader.java, mondrian/src/main/java/mondrian/rolap/DelegatingMemberReader.java, mondrian/src/main/java/mondrian/rolap/MemberReader.java, mondrian/src/main/java/mondrian/rolap/NoCacheMemberReader.java, mondrian/src/main/java/mondrian/rolap/RolapCubeHierarchy.java, mondrian/src/main/java/mondrian/rolap/RolapNativeSet.java, mondrian/src/main/java/mondrian/rolap/RolapSchemaReader.java, mondrian/src/main/java/mondrian/rolap/SmartMemberReader.java, mondrian/src/main/java/mondrian/rolap/SqlMemberSource.java, mondrian/src/main/java/mondrian/rolap/SqlStatement.java
=> [MONDRIAN-2720] - GetMemberChildren should not return actual members for distinct count optimization

mondrian/src/main/java/mondrian/rolap/MemberCacheHelper.java
=> [SP-6365] - Backport of MONDRIAN-2733 - Performance issues when Mondrian is dealing with large GetMemberChildren queue (9.5 Suite)

mondrian/src/site/resources/doc/developer.html
[PPP-4949] Vulnerable Component: Xerces
[PPP-4949]: https://hv-eng.atlassian.net/browse/PPP-4949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PPP-4949] Vulnerable Component: Xerces

mondrian/src/main/java/mondrian/rolap/SqlMemberSource.java
Removing order by in count queries for getMemberChildren/countMemberChildren methods
@smmribeiro 
@renato-s 
=> MONDRIAN-2742   Incorrect query when dealing with large GetMemberChildren queue on MS SQL Server

mondrian/src/site/resources/doc/developer.html
[PPP-4949] Vulnerable Component: XercesImpl
[PPP-4949]: https://hv-eng.atlassian.net/browse/PPP-4949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PPP-4949] Vulnerable Component: XercesImpl

assemblies/psw-ce/pom.xml, mondrian/README.md, mondrian/pom.xml, pom.xml
=> Addresses BACKLOG-40293: bump Mondrian version

mondrian/README.md, mondrian/pom.xml, mondrian/src/it/java/mondrian/test/Olap4jTckTest.java, pom.xml
=> fix: integration tests execution

mondrian/src/it/java/mondrian/tui/XmlUtilTest.java, mondrian/src/it/java/mondrian/xmla/XmlaBaseTestCase.java, mondrian/src/it/java/mondrian/xmla/XmlaBasicTest.java, mondrian/src/it/java/mondrian/xmla/XmlaBasicTest.ref.xml, mondrian/src/it/java/mondrian/xmla/XmlaDimensionPropertiesTest.ref.xml, mondrian/src/it/java/mondrian/xmla/XmlaExcel2000Test.ref.xml, mondrian/src/it/java/mondrian/xmla/XmlaExcel2007Test.ref.xml, mondrian/src/it/java/mondrian/xmla/XmlaExcelXPTest.ref.xml, mondrian/src/it/java/mondrian/xmla/XmlaMetaDataConstraintsTest.ref.xml, mondrian/src/it/java/mondrian/xmla/XmlaTabularTest.ref.xml, mondrian/src/it/java/mondrian/xmla/test/XmlaTest.java, mondrian/src/main/java/mondrian/tui/XmlaSupport.java, mondrian/src/main/java/mondrian/xmla/XmlaHandler.java, mondrian/src/main/java/mondrian/xmla/XmlaServlet.java, mondrian/src/main/java/mondrian/xmla/XmlaUtil.java, mondrian/src/main/java/mondrian/xmla/impl/DefaultXmlaServlet.java
=> feat: remove XMLA namespace prefix from XMLA handler [BACKLOG-40293]

mondrian/src/it/java/mondrian/xmla/XmlaBasicTest.ref.xml, mondrian/src/main/java/mondrian/xmla/PropertyDefinition.java
=> Addresses BACKLOG-40328: add support for new XMLA properties

mondrian/src/it/java/mondrian/xmla/XmlaBasicTest.ref.xml, mondrian/src/it/java/mondrian/xmla/XmlaExcel2000Test.ref.xml, mondrian/src/it/java/mondrian/xmla/XmlaExcelXPTest.ref.xml, mondrian/src/main/java/mondrian/olap/MondrianServer.java, mondrian/src/main/java/mondrian/olap4j/MondrianOlap4jConnection.java, mondrian/src/main/java/mondrian/server/FileRepository.java, mondrian/src/main/java/mondrian/server/MondrianServerImpl.java, mondrian/src/main/java/mondrian/xmla/RowsetDefinition.java
=> Addresses BACKLOG-40293: add DISCOVER_XML_METADATA rowset

mondrian/src/it/java/mondrian/server/FileRepositoryTest.java, mondrian/src/it/java/mondrian/tui/XmlUtilTest.java, mondrian/src/it/java/mondrian/xmla/XmlaBaseTestCase.java, mondrian/src/it/java/mondrian/xmla/XmlaBasicTest.java, mondrian/src/it/java/mondrian/xmla/test/XmlaTest.java, mondrian/src/main/java/mondrian/tui/XmlaSupport.java, mondrian/src/main/java/mondrian/xmla/PropertyDefinition.java, mondrian/src/main/java/mondrian/xmla/XmlaServlet.java, mondrian/src/main/java/mondrian/xmla/XmlaUtil.java
=> chore: update license headers

mondrian/README.md, mondrian/pom.xml, mondrian/src/main/java/mondrian/server/FileRepository.java
=> Addresses BACKLOG-40293: datasource info extraction

workbench/src/main/java/mondrian/gui/SchemaPropertyCellEditor.java, workbench/src/main/java/mondrian/olap/Mondrian_SW.xml
=> [PSW-278] - List of dialects not sorted correctly

mondrian/README.md
Repository one.hitachivantara.com is for Pentaho R&D internal usage.
=> [CLEANUP] remove unnecessary server config text

mondrian/pom.xml, mondrian/src/main/java/mondrian/tui/XmlUtil.java, mondrian/src/main/java/mondrian/util/XmlParserFactoryProducer.java, mondrian/src/main/java/mondrian/xmla/XmlaUtil.java, mondrian/src/main/java/mondrian/xmla/impl/DefaultXmlaServlet.java
[BACKLOG-36134]-Consolidate Redundant Secure XML Parsing code
[BACKLOG-36134]: https://hv-eng.atlassian.net/browse/BACKLOG-36134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-36134]-Consolidate Redundant Secure XML Parsing code

mondrian/pom.xml, mondrian/src/main/java/mondrian/tui/XmlUtil.java, mondrian/src/main/java/mondrian/util/XmlParserFactoryProducer.java, mondrian/src/main/java/mondrian/xmla/XmlaUtil.java, mondrian/src/main/java/mondrian/xmla/impl/DefaultXmlaServlet.java
[REVERT]-BACKLOG-36134-Consolidate Redundant Secure XML Parsing code
=> [REVERT]-BACKLOG-36134-Consolidate Redundant Secure XML Parsing code

mondrian/src/main/resources/mondrian.xsd
Related to SME-285.
Following https://github.com/pentaho/mondrian/pull/1397, here are changes related to some of the `TODO`s present in the first version.
=> feat: Perform changes to new XSD after feedback

mondrian/src/main/resources/mondrian.xsd
Relates to SME-352.
Add constraint to ensure cube names are unique within a model
=> feat: Add unique name constraint for cubes [SME-352]

mondrian/src/main/resources/mondrian.xsd
https://hv-eng.atlassian.net/browse/SME-313
Fix incorrectly changed attributes type that were incorrectly changed to FormulaType
=> fix: fix FormulaType definition [SME-313] 

mondrian/src/it/java/mondrian/olap/IdBatchResolverTest.java, mondrian/src/main/java/mondrian/rolap/MemberCacheHelper.java, mondrian/src/main/java/mondrian/rolap/SmartMemberReader.java
Addresses: SP-6653
Backport from f68b5817a
=> fix: no cache usage on empty children requests [MONDRIAN-2646] [OLP-187] [SP-6653] (#1431)

mondrian/src/main/resources/mondrian.xsd
Create new abstract class to facilitate JSON schema generation for SME
=> feat: Create RelationOrJoinType [SME-536] [SME-548]

mondrian/build.xml
[BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures
[BACKLOG-43874]: https://hv-eng.atlassian.net/browse/BACKLOG-43874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures

mondrian/build.xml
[BACKLOG-45596]-Upgrade JDK properties from 11 to 17
[BACKLOG-45596]: https://hv-eng.atlassian.net/browse/BACKLOG-45596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-45596]-Upgrade JDK properties from 11 to 17
