src/main/mondrian/spi/impl/ImpalaDialect.java
This corrects an issue with drillthrough when aliases have spaces, and
also allows fields/tables to have keywords present in their names.
=> [MONDRIAN-2145] Sets the identifier quote string for Impala to `.

src/main/mondrian/udf/CurrentDateMemberUdf.java, testsrc/main/mondrian/udf/CurrentDateMemberUdfTest.java
@lucboudreau, would you mind review/merge?
There are two commits:
1) Junit test which illustrates an problem.
2) Fix.
Files were changed according to mondrian formatting rules.
Brief sense of the fix: now we return not an empty MemberType but MemberType with dimension info in case if we can get one from parameters.
=> MONDRIAN-2256

bin/checkFile.awk, src/main/mondrian/rolap/SqlTupleReader.java, testsrc/main/mondrian/rolap/TestAggregationManager.java, testsrc/main/mondrian/rolap/aggmatcher/MultipleColsInTupleAggTest.java, testsrc/main/mondrian/rolap/aggmatcher/multiple_cols_in_tuple_agg.csv, testsrc/main/mondrian/test/loader/CsvDBTestCase.java
the filter condition excludes measures and the level has extra columns
(properties, ordinalColumn, etc.)
Addresses a couple of cases mishandled by SqlTupleReader when joining
collapsed attributes which have additional columns that need to be
read from the dimension table(s).  For example, there may be need to
read ordinal column, or property values.  The existing logic worked
well enough in most cases, but made two faulty assumptions:
1) It assumed the aggstar will be joined in via the constraint, which
may not always be the case.
2) It assumed using the dimensional attribute in the select list
instead of the agg star attribute wouldn't have an impact.  This
normally shouldn't matter--the collapsed attribute and the
corresponding attribute from the dim table are identical-- but native …
=> [ANALYZER-2655] Invalid Agg table SQL generated by native filter when

bin/checkFile.awk, src/main/mondrian/rolap/SqlTupleReader.java, testsrc/main/mondrian/rolap/TestAggregationManager.java, testsrc/main/mondrian/rolap/aggmatcher/MultipleColsInTupleAggTest.java, testsrc/main/mondrian/rolap/aggmatcher/multiple_cols_in_tuple_agg.csv, testsrc/main/mondrian/test/loader/CsvDBTestCase.java
the filter condition excludes measures and the level has extra columns
(properties, ordinalColumn, etc.)
Addresses a couple of cases mishandled by SqlTupleReader when joining
collapsed attributes which have additional columns that need to be
read from the dimension table(s).  For example, there may be need to
read ordinal column, or property values.  The existing logic worked
well enough in most cases, but made two faulty assumptions:
1) It assumed the aggstar will be joined in via the constraint, which
may not always be the case.
2) It assumed using the dimensional attribute in the select list
instead of the agg star attribute wouldn't have an impact.  This
normally shouldn't matter--the collapsed attribute and the
corresponding attribute from the dim table are identical-- but native …
=> [SP-1703][ANALYZER-2655] Invalid Agg table SQL generated by native filter when

src/main/mondrian/olap/DelegatingSchemaReader.java, src/main/mondrian/olap/IdBatchResolver.java, src/main/mondrian/olap/IdentifierVisitor.java, src/main/mondrian/olap/MondrianProperties.xml, src/main/mondrian/olap/Query.java, src/main/mondrian/olap/SchemaReader.java, src/main/mondrian/olap/Util.java, src/main/mondrian/olap/ValidatorImpl.java, src/main/mondrian/rolap/ChildByNameConstraint.java, src/main/mondrian/rolap/MemberCacheHelper.java, src/main/mondrian/rolap/RolapSchemaReader.java, src/main/mondrian/rolap/SmartIncrementalCache.java, src/main/mondrian/rolap/SqlConstraintFactory.java, src/main/mondrian/rolap/SqlConstraintUtils.java, testsrc/main/mondrian/olap/IdBatchResolverTest.java, testsrc/main/mondrian/rolap/BatchTestCase.java, testsrc/main/mondrian/rolap/DataSourceChangeListenerTest.java, testsrc/main/mondrian/rolap/MemberCacheHelperTest.java, testsrc/main/mondrian/rolap/NonEmptyTest.java, testsrc/main/mondrian/rolap/VirtualCubeTest.java, testsrc/main/mondrian/rolap/sql/EffectiveMemberCacheTest.java, testsrc/main/mondrian/test/Main.java, testsrc/main/mondrian/test/NativeSetEvaluationTest.java
dimension members.
1) Introduces a "batch resolution" phase prior to final expression
resolution which collects child name references and loads them at the
same time.  This avoids the one-at-a-time SQL queries for each child
member reference within an expression.  IdBatchResolver is the
relevant class.
2) To better suppport (1), this change also introduces a new caching
mechanism for ChildByNameConstraints.  If the child members { [Bob],
[Joe], [Bill] } have already been cached, MemberCacheHelper is now
smart enough to retrieve any subset of what has formerly been loaded.
This new functionanlity only works with ChildByNameConstraint checks,
since it depends on lookups by name.
3) To better handle small levels (under 300 members), this change also
adds a check for level cardinality when …
=> [BACKLOG-2384] Changes to better support loading and caching of

src/main/mondrian/rolap/sql/SqlQuery.java, testsrc/main/mondrian/rolap/sql/CodeSetTest.java, testsrc/main/mondrian/test/Main.java
There is a fix proposed by Luc Boudreau and unit tests.
=> MONDRIAN-2335: SQL for dialect='postgres' in Measure expression is never used to generate native SQL

build.xml
(cherry picked from commit fe7baf0)
@lucboudreau
=> [CLEANUP] Allows compilation on 1.6+ instead of only 1.6.

doc/vba_functions.html, src/main/mondrian/olap/fun/vba/Vba.java, testsrc/main/mondrian/olap/fun/vba/VbaTest.java
- revert changes related to Interval.d from commit 1ee115751dfb9e5520d411a0b37232229728b409
- change the behaviour of dateDiff function, by manually replacing Interval.d with Interval.y
- add a test to verbose the difference between 'd' and 'y' for DatePart function (https://msdn.microsoft.com/en-us/library/20ee97hz(v=vs.90).aspx)
@mkambol, review it please. I hope this will solve the problem.
/cc @lucboudreau
=> [MONDRIAN-2319] - Calculating Date difference produce wrong result

src/main/mondrian/olap/fun/UdfResolver.java, testsrc/main/mondrian/rolap/FastBatchingCellReaderTest.java
@mkambol, @lucboudreau, here is backport of https://github.com/pentaho/mondrian/commit/f6875377f8685517575b6a82850b26dd97da798b, https://github.com/pentaho/mondrian/commit/ba0830d35c87de0c42061b9567463b5cde993462 and https://github.com/pentaho/mondrian/commit/d0fc2f09fd2513518d09b03e084eec4c9cac5dc3 to 5.4 branch, thanks
=> SP-1945 - Backport of MONDRIAN-2251 - Exceeding CellBatchSize when evaluating a UDF causes an error. (5.4 Suite)

src/main/mondrian/olap/DrillThrough.java, src/main/mondrian/olap4j/MondrianOlap4jCell.java, src/main/mondrian/rolap/RolapAggregationManager.java, src/main/mondrian/rolap/RolapCell.java, src/main/mondrian/rolap/agg/AggregationManager.java, src/main/mondrian/rolap/agg/DrillThroughCellRequest.java, src/main/mondrian/rolap/agg/DrillThroughQuerySpec.java, testsrc/main/mondrian/test/DrillThroughTest.java
When Analyzer issues a DT, it includes (by default) a RETURNS clause
including all available members.  In a virtual cube this may include
some non-conforming, inapplicable members.  To address this case,
we now capture the list of inapplicable members so they can be
specially handled.  All inapplicable members result in a placeholder
field in the DT resultset with a value of NULL.
=> [ANALYZER-3017]  Drillthrough in Analyzer against a Virtual cube fails

src/main/mondrian/calc/impl/AbstractEndToEndTupleList.java
The following query could trip it:
WITH
SET [parentNamedSet] AS '[childNamedSet]'
SET [childNamedSet] AS 'HEAD({[Product].[All Products]})'
SELECT
[parentNamedSet] ON 0
FROM [Sales]
[childNamedSet] is evaluated during evaluation of the parent named
set, which results in a tupleList with position callback.  The
assertion checks that the backing tupleList isn’t one of these
“position callback supporting” tuplelists, but that can happen with
this sort of nesting.
=> [TEST]  Removing invalid assertion that can get hit with nested named sets.

src/main/mondrian/rolap/CacheControlImpl.java, src/main/mondrian/rolap/RolapNativeRegistry.java, src/main/mondrian/rolap/RolapNativeSet.java, testsrc/main/mondrian/rolap/CacheControlTest.java
@mkambol, here is backport of http://jira.pentaho.com/browse/MONDRIAN-2366 to 3.10.0. Thanks
=> Backport of MONDRIAN-2366 - CacheControl.flush(MemberSet) does not flush NativeSet member caches. (5.4 Suite)

src/main/mondrian/olap/Mondrian.xml, src/main/mondrian/rolap/RolapLevel.java, src/main/mondrian/rolap/SqlTupleReader.java, src/main/mondrian/rolap/aggmatcher/AggStar.java, src/main/mondrian/rolap/aggmatcher/DefaultRecognizer.java, src/main/mondrian/rolap/aggmatcher/ExplicitRecognizer.java, src/main/mondrian/rolap/aggmatcher/ExplicitRules.java, src/main/mondrian/rolap/aggmatcher/JdbcSchema.java, src/main/mondrian/rolap/aggmatcher/Recognizer.java, testsrc/main/mondrian/rolap/aggmatcher/ExplicitRecognizerTest.java, testsrc/main/mondrian/rolap/aggmatcher/explicit_aggs.csv, testsrc/main/mondrian/test/Main.java
hierarchy's levels so to avoid joins to the dimension tables
This change introduces support for extra level columns when using an
explicitly defined aggregate level.  These columns can be defined by
adding ordinalColumn and captionColumn attributes on an <AggLevel>, as
well as nesting <AggLevelProperties> under an <AggLevel>.  When
constructing SqlTupleReader queries to pull level metadata we'll now
check whether any "extra" columns have a mapping to the aggregate
table.  If not, the old behavior of joining agg table to dimension
table will be used as a fall back.
=> [MONDRIAN-1495] Allow Aggregate levels to use more attributes from

src/main/mondrian/olap/DrillThrough.java, src/main/mondrian/olap4j/MondrianOlap4jCell.java, src/main/mondrian/rolap/RolapAggregationManager.java, src/main/mondrian/rolap/RolapCell.java, src/main/mondrian/rolap/agg/AggregationManager.java, src/main/mondrian/rolap/agg/DrillThroughCellRequest.java, src/main/mondrian/rolap/agg/DrillThroughQuerySpec.java, testsrc/main/mondrian/test/DrillThroughTest.java
cube fails
When Analyzer issues a DT, it includes (by default) a RETURNS clause
including all available members.  In a virtual cube this may include
some non-conforming, inapplicable members.  To address this case,
we now capture the list of inapplicable members so they can be
specially handled.  All inapplicable members result in a placeholder
field in the DT resultset with a value of NULL.
(cherry picked from commit 6d9c413)
@kurtwalker
=> [SP-2038][ANALYZER-3017]  Drillthrough in Analyzer against a Virtual

src/main/mondrian/olap/DrillThrough.java, src/main/mondrian/olap4j/MondrianOlap4jCell.java, src/main/mondrian/rolap/RolapAggregationManager.java, src/main/mondrian/rolap/RolapCell.java, src/main/mondrian/rolap/agg/AggregationManager.java, src/main/mondrian/rolap/agg/DrillThroughCellRequest.java, src/main/mondrian/rolap/agg/DrillThroughQuerySpec.java, testsrc/main/mondrian/test/DrillThroughTest.java
cube fails
When Analyzer issues a DT, it includes (by default) a RETURNS clause
including all available members.  In a virtual cube this may include
some non-conforming, inapplicable members.  To address this case,
we now capture the list of inapplicable members so they can be
specially handled.  All inapplicable members result in a placeholder
field in the DT resultset with a value of NULL.
(cherry picked from commit 6d9c413)
5.3 backport
@kurtwalker
=> [SP-2037][ANALYZER-3017]  Drillthrough in Analyzer against a Virtual

src/main/mondrian/rolap/agg/AggregationManager.java, testsrc/main/mondrian/rolap/aggmatcher/DefaultRecognizerTest.java, testsrc/main/mondrian/rolap/aggmatcher/ExplicitRecognizerTest.java
if levels involved are set with uniqueMembers=true
First noticed when a cube was set with a distinct-count default
measure, which caused unexpected agg table misses during
SqlTupleReader queries (which in many cases will be evaluated in the
context of the default measure).
This occurred because the levelBitKey would be set with just the child
level's bit set, even though the aggregate tables bitkey would include
each parent level as well.  It's okay to match when the parent bitkeys
are set in this case, because presence of the parent columns does not
effect granularity.
@kurtwalker
=> [MONDRIAN-2376] distinct-count measures could cause an agg table miss

src/main/mondrian/rolap/agg/AggregationManager.java, testsrc/main/mondrian/rolap/aggmatcher/DefaultRecognizerTest.java, testsrc/main/mondrian/rolap/aggmatcher/ExplicitRecognizerTest.java
@mbatchelor, @pamval could you review it, please? Here is origin issue's PR: 6468606
=> SP-2058 - Backport of MONDRIAN-2376 - Aggregate table not used for native tuple query if default cube measure is distinct-count (5.3 Suite)

src/main/mondrian/olap/fun/AggregateFunDef.java, src/main/mondrian/rolap/CompoundPredicateInfo.java, src/main/mondrian/rolap/FastBatchingCellReader.java, src/main/mondrian/rolap/RolapAggregationManager.java, src/main/mondrian/rolap/RolapEvaluator.java, src/main/mondrian/rolap/agg/AggregationKey.java, src/main/mondrian/rolap/agg/CellRequest.java, src/main/mondrian/rolap/agg/SegmentCacheManager.java, src/main/mondrian/rolap/cache/SegmentCacheIndexImpl.java, testsrc/main/mondrian/rolap/BatchTestCase.java, testsrc/main/mondrian/rolap/FastBatchingCellReaderTest.java, testsrc/main/mondrian/rolap/RolapEvaluatorTest.java, testsrc/main/mondrian/rolap/agg/AggregationOnDistinctCountMeasuresTest.java, testsrc/main/mondrian/test/CompoundSlicerTest.java, testsrc/main/mondrian/test/TestContext.java
distinct measures and compound slicers
This commit includes the following changes to reduce the overhead of
distinct-count measures being evaluated in the context of a compound
slicer:
1)  Compound predicates for the slicer are constructed in the
evaluator.  This allows the slicer predicates to be constructed a
single time in most cases, rather than once per cell request.
2) Similarly, the compound predicate string representation for the slicer
is also constructed in the evaluator.
3) AggregateFunDef updated to avoid unnecessary tuple optimization
when tuplelist is supportable within an IN list.  The tuple
optimization algorithm is expensive and we should avoid it when
unnecessary.
To support 1 and 2, the logic in RolapAggregationManager for
constructing compound predicates has been …
=> [MONDRIAN-2403] Severe performance issue with reports containing count

src/main/mondrian/gui/Workbench.java
Updating KETTLE_PLUGIN_BASE_FOLDERS to include the plugin dir
to make sure the dataservices plugin is found and loaded.
(cherry picked from commit 9057afe)
@dkincade
=> [BACKLOG-5370]  "Pentaho Data Services" database type not in list

build.xml
@lucboudreau 
This one's for 3.9.
=> [CLEANUP]  Removing jdk15 compilation.  jdk16+ is required.

src/main/mondrian/rolap/MemberExcludeConstraint.java, src/main/mondrian/rolap/RolapNativeSet.java, src/main/mondrian/rolap/RolapNativeTopCount.java, src/main/mondrian/rolap/SqlConstraintUtils.java, src/main/mondrian/rolap/SqlTupleReader.java, testsrc/main/mondrian/rolap/RolapNativeTopCountTest.java, testsrc/main/mondrian/rolap/RolapNativeTopCountTestCases.java, testsrc/main/mondrian/rolap/RolapNativeTopCountVersusNonNativeTest.java, testsrc/main/mondrian/rolap/TopCountNativeEvaluatorTest.java, testsrc/main/mondrian/rolap/TopCountWithTwoParamsVersusHeadTest.java, testsrc/main/mondrian/test/AccessControlTest.java, testsrc/main/mondrian/test/FoodMartTestCase.java, testsrc/main/mondrian/test/Main.java
- adopt changes from dbdc2bfe1d05b8f11a82f3d3532adce3132d0d7c
- the idea is to complete output data with result of one new query, where existing rows are filtered
- add tests
@lucboudreau, @mkambol, review it please
=> [MONDRIAN-1272] - Native Top Count cannot handle empty members

src/main/mondrian/rolap/RolapNativeSql.java, testsrc/main/mondrian/rolap/NativeFilterAgainstAggTableTest.java, testsrc/main/mondrian/rolap/NativeFilterMatchingTest.java, testsrc/main/mondrian/test/Main.java
- use aggregation table's rollup aggregator instead of measure's
- add tests
(cherry picked from commit fab0acb)
@mkambol, @lucboudreau, review it please. This is a backport of https://github.com/pentaho/mondrian/pull/573
=> [SP-2168] - Backport of MONDRIAN-2155 - Invalid results when using native filter and topcount with aggregate table measures (6.0 Suite)

src/main/mondrian/rolap/MemberExcludeConstraint.java, src/main/mondrian/rolap/RolapNativeSet.java, src/main/mondrian/rolap/RolapNativeTopCount.java, src/main/mondrian/rolap/SqlConstraintUtils.java, src/main/mondrian/rolap/SqlTupleReader.java, testsrc/main/mondrian/rolap/RolapNativeTopCountTest.java, testsrc/main/mondrian/rolap/RolapNativeTopCountTestCases.java, testsrc/main/mondrian/rolap/RolapNativeTopCountVersusNonNativeTest.java, testsrc/main/mondrian/rolap/TopCountNativeEvaluatorTest.java, testsrc/main/mondrian/rolap/TopCountWithTwoParamsVersusHeadTest.java, testsrc/main/mondrian/test/AccessControlTest.java, testsrc/main/mondrian/test/FoodMartTestCase.java, testsrc/main/mondrian/test/Main.java
@mkambol, @lucboudreau, review it please. This is a backport of https://github.com/pentaho/mondrian/pull/566
=> [SP-2167] - Backport of MONDRIAN-2394 - Mondrian TopCount returns only non empty tuples when native.topcount is enabled (6.0 Suite)

ivy.xml
Adding the MySQL driver as a dependency will prevent a lot of SSH and SCP operations on CI servers. It is OK to add MySQL connector as a test dependency; it is part of other projects as a test dependency as well, like analyzer.
=> [TEST] Adds the MySQL driver for testing convenience

src/main/mondrian/spi/impl/ImpalaDialect.java, testsrc/main/mondrian/spi/impl/ImpalaDialectTest.java, testsrc/main/mondrian/test/Main.java
- explicitly cast values to string when generating regex condition for Impala
- add tests
@mkambol, @lucboudreau, review it please.
I checked several DBs to find out how do they react on similar situation.
* MySql -- implicitly converts int to string
* MsSql -- Mondrian does not support generating regex conditions for it, so no problem there
* Oracle -- works fine w/o any explicit cast
* Postgres -- looks like similar problem has been reported, it was fixed in the same manner by https://github.com/pentaho/mondrian/commit/3c5d6b7b86f09fc5ab1262afdfa30c0f8d97cb2a.
To sum up, I believe my fix is quite enough for now.
=> [MONDRIAN-2433] - Filtering in analyzer report for Integer, Numeric values returns UPPER() error message with Impala

src/main/mondrian/rolap/DefaultTupleConstraint.java, src/main/mondrian/rolap/DescendantsConstraint.java, src/main/mondrian/rolap/MemberExcludeConstraint.java, src/main/mondrian/rolap/RolapNativeSet.java, src/main/mondrian/rolap/RolapNativeTopCount.java, src/main/mondrian/rolap/SqlContextConstraint.java, src/main/mondrian/rolap/SqlTupleReader.java, src/main/mondrian/rolap/sql/MemberKeyConstraint.java, src/main/mondrian/rolap/sql/TupleConstraint.java, testsrc/main/mondrian/test/NativeSetEvaluationTest.java
The 2 arg form of TC/BC should return the tuple set in its
natural order.  Because of this, we cannot join to the fact table
when determining the set.  Native eval can still be  valuable,
however, since member constraints and limiting sql to top N rows
can reduce set evaluation time.
This change makes the isJoinRequired method of TopCountConstraint
conditional on whether an orderByExpression is present.  It
also adds logic to determine whether the constraint is valid, since
push down with the 2 arg form of TC can only be done if
a single crossjoin arg is present.
http://jira.pentaho.com/browse/MONDRIAN-2430
@lucboudreau
=> [MONDRIAN-2430]  The 2 arg form of TopCount can perform badly

testsrc/main/mondrian/test/Main.java
that's not being backported.
@lucboudreau
=> [CLEANUP]  removing reference to a test class originating from a commit

src/main/mondrian/rolap/RolapNativeSql.java, testsrc/main/mondrian/rolap/RolapNativeSqlInjectionTest.java, testsrc/main/mondrian/rolap/RolapNativeSql_NumberSqlCompiler_Test.java, testsrc/main/mondrian/test/Main.java
- prohibit invalid decimal literals in NumberSqlCompiler
- add tests
@lucboudreau, @mkambol, @kurtwalker, review it please.
=> [MONDRIAN-2436] - SQL Injection through MDX Filter

src/main/mondrian/spi/impl/ImpalaDialect.java, testsrc/main/mondrian/spi/impl/ImpalaDialectTest.java, testsrc/main/mondrian/test/Main.java
- explicitly cast values to string when generating regex condition for Impala
- add tests
(cherry picked from commit 040b5c4)
@mkambol, @lucboudreau, review it please. This is a backport of https://github.com/pentaho/mondrian/pull/597
=> [SP-2326] - Backport of MONDRIAN-2433 - Filtering in analyzer report for Integer, Numeric values returns UPPER() error message with Impala (6.0 Suite)

testsrc/main/mondrian/rolap/TestAggregationManager.java
agg tables.  Was using DefaultConstraint, so not
attempting to join to the agg table since the level
cardinality fell below threshold.
@lucboudreau
=> [TEST] fixing testAggregatingTuples when run with

src/main/mondrian/rolap/RolapNativeSql.java, testsrc/main/mondrian/rolap/NumberSqlCompilerTest.java, testsrc/main/mondrian/rolap/RolapNativeSqlInjectionTest.java, testsrc/main/mondrian/test/Main.java
- prohibit invalid decimal literals in NumberSqlCompiler, throw exception in such cases
- to do it, introduce a pattern for expected decimal values, as Double.parseDouble() accepts such values as 'NaN', 'Infinity' and others
- add tests
(cherry picked from commits 232f75e, 7dea3f6, 37a2c2d, ba79374)
@lucboudreau, @mkambol, review it please. This is a backport of #607, #608, #609, #614
=> [SP-2314] - Backport of MONDRIAN-2436 - SQL Injection through MDX Filter (5.4 Suite)

src/main/mondrian/spi/impl/ImpalaDialect.java, testsrc/main/mondrian/spi/impl/ImpalaDialectTest.java, testsrc/main/mondrian/test/Main.java
- explicitly cast values to string when generating regex condition for Impala
- add tests
(cherry picked from commit 040b5c4)
@mkambol, @lucboudreau, review it please. This is a backport of https://github.com/pentaho/mondrian/pull/597.
=> [SP-2327] - Backport of MONDRIAN-2433 - Filtering in analyzer report for Integer, Numeric values returns UPPER() error message with Impala (5.4 Suite)

src/main/mondrian/rolap/RolapNativeSql.java, testsrc/main/mondrian/rolap/NumberSqlCompilerTest.java, testsrc/main/mondrian/rolap/RolapNativeSqlInjectionTest.java, testsrc/main/mondrian/test/Main.java
- prohibit invalid decimal literals in NumberSqlCompiler, throw exception in such cases
- add tests
(cherry picked from commits 232f75e, 7dea3f6, 37a2c2d)
@mkambol, @lucboudreau, review it please. This is a backport of https://github.com/pentaho/mondrian/pull/607, https://github.com/pentaho/mondrian/pull/608, https://github.com/pentaho/mondrian/pull/609
=> [SP-2313] - Backport of MONDRIAN-2436 - SQL Injection through MDX Filter (6.0 Suite)

src/main/mondrian/rolap/RolapCube.java, testsrc/main/mondrian/test/SchemaTest.java
This will enable a better way for determining which "visible=false" elements should always remain hidden from an Analyzer user. We can look for that annotation rather than a specific named element (like Fact count).
=> [BACKLOG-5898] - Adding an "Internal Use" annotation to the implicit "Fact Count" measure.

src/main/mondrian/rolap/RolapSchema.java, testsrc/main/mondrian/rolap/RolapSchemaTest.java, testsrc/main/mondrian/rolap/agg/AggregationOnInvalidRoleTest.java, testsrc/main/mondrian/rolap/agg/AggregationOnInvalidRoleWhenNotIgnoringTest.java, testsrc/main/mondrian/rolap/agg/mondrian_2225.csv, testsrc/main/mondrian/test/FoodMartTestCase.java, testsrc/main/mondrian/test/Main.java, testsrc/main/mondrian/test/PropertyRestoringTestCase.java
- restrict hierarchy entirely if it contains no members and was initially defined with CUSTOM access
- introduce separate methods for each OlapElement to be used in granting routine
- introduce PropertyRestoringTestCase to be a parent for those tests that need changed properties
- add tests for the ticket's case
(cherry picked from commit 8dfab89)
@mkambol, @lucboudreau, review it please. This is a backport of https://github.com/pentaho/mondrian/pull/599
=> [SP-2375] - Backport of MONDRIAN-2225 - Using aggregations with data restrictions return error (6.0 Suite)

src/main/mondrian/rolap/RolapSchema.java, testsrc/main/mondrian/rolap/RolapSchemaTest.java, testsrc/main/mondrian/rolap/agg/AggregationOnInvalidRoleTest.java, testsrc/main/mondrian/rolap/agg/AggregationOnInvalidRoleWhenNotIgnoringTest.java, testsrc/main/mondrian/rolap/agg/mondrian_2225.csv, testsrc/main/mondrian/test/FoodMartTestCase.java, testsrc/main/mondrian/test/Main.java, testsrc/main/mondrian/test/PropertyRestoringTestCase.java
- restrict hierarchy entirely if it contains no members and was initially defined with CUSTOM access
- introduce separate methods for each OlapElement to be used in granting routine
- introduce PropertyRestoringTestCase to be a parent for those tests that need changed properties
- add tests for the ticket's case
(adopted from commit 8dfab89)
@mkambol, @lucboudreau, review it please. This is a backport of https://github.com/pentaho/mondrian/pull/599
=> [SP-2376] - Backport of MONDRIAN-2225 - Using aggregations with data restrictions return error (5.4 Suite)

testsrc/main/mondrian/rolap/agg/SegmentBuilderTest.java
- prohibit `testSegmentCreationForBoolean_*` to be executed with Oracle connection
@mkambol, @lucboudreau, @kurtwalker, review it please
=> [TEST] - Make SegmentBuilderTest tolerant to different environments

testsrc/main/mondrian/rolap/RolapNativeSqlInjectionTest.java
- force Mondrian to open a fresh connection as it compels it to re-create schemas and, consequently, RolapNativeRegistry, where native-related instances are stored
@mkambol, @lucboudreau, @kurtwalker, review it please
=> [TEST] - Make RolapNativeSqlInjectionTest tolerant to different environments

ivy.xml, src/main/mondrian/tui/NamespaceContextImpl.java, src/main/mondrian/tui/XmlUtil.java, src/main/mondrian/tui/XmlaSupport.java, testsrc/main/mondrian/test/Main.java, testsrc/main/mondrian/tui/NamespaceContextImplTest.java, testsrc/main/mondrian/tui/XmlUtilTest.java
This change refactors parts of XmlUtil and XmlaSupport which were
dependent on Xalan 2.6, switching to standard java.xml.xpath.
A number of unused methods were also cleared out.
http://jira.pentaho.com/browse/BACKLOG-6084
@lucboudreau
=> [BACKLOG-6084]  Remove xalan dependency from Mondrian

src/main/mondrian/olap/MondrianProperties.xml, src/main/mondrian/olap/fun/CrossJoinFunDef.java, src/main/mondrian/olap/fun/FilterFunDef.java, src/main/mondrian/olap/fun/FunUtil.java, src/main/mondrian/olap/fun/GenerateFunDef.java, src/main/mondrian/rolap/RolapResult.java, src/main/mondrian/rolap/SqlMemberSource.java, src/main/mondrian/rolap/SqlTupleReader.java, src/main/mondrian/rolap/agg/SegmentLoader.java, src/main/mondrian/util/CancellationChecker.java, testsrc/main/mondrian/rolap/CancellationTest.java, testsrc/main/mondrian/rolap/agg/AggregationOnDistinctCountMeasuresTest.java, testsrc/main/mondrian/test/BasicQueryTest.java
@lucboudreau, @mkambol, would you mind of reviewing/merging?
=> [MONDRIAN-2279] - When a query is cancelled or times out, Mondrian may continue iterating over large tuple lists

src/main/mondrian/olap/MondrianProperties.xml, src/main/mondrian/olap/fun/CrossJoinFunDef.java, src/main/mondrian/olap/fun/FilterFunDef.java, src/main/mondrian/olap/fun/FunUtil.java, src/main/mondrian/olap/fun/GenerateFunDef.java, src/main/mondrian/rolap/RolapResult.java, src/main/mondrian/rolap/SqlMemberSource.java, src/main/mondrian/rolap/SqlTupleReader.java, src/main/mondrian/rolap/agg/SegmentLoader.java, src/main/mondrian/util/CancellationChecker.java, testsrc/main/mondrian/rolap/CancellationTest.java, testsrc/main/mondrian/rolap/agg/AggregationOnDistinctCountMeasuresTest.java, testsrc/main/mondrian/test/BasicQueryTest.java
@mkambol, @pamval here is backport of #639 and #643 to 3.11 (6.0) branch. Backport to 5.4 is here: https://github.com/pentaho/mondrian/pull/652. Thsnks.
=> [Sp-2458] - Backport of MONDRIAN-2279 - When a query is cancelled or times out, Mondrian may continue iterating over large tuple lists (6.0 Suite)

src/main/mondrian/olap/MondrianProperties.xml, src/main/mondrian/olap/fun/CrossJoinFunDef.java, src/main/mondrian/olap/fun/FilterFunDef.java, src/main/mondrian/olap/fun/FunUtil.java, src/main/mondrian/olap/fun/GenerateFunDef.java, src/main/mondrian/rolap/RolapResult.java, src/main/mondrian/rolap/SqlMemberSource.java, src/main/mondrian/rolap/SqlTupleReader.java, src/main/mondrian/rolap/agg/SegmentLoader.java, src/main/mondrian/util/CancellationChecker.java, testsrc/main/mondrian/rolap/CancellationTest.java, testsrc/main/mondrian/rolap/agg/AggregationOnDistinctCountMeasuresTest.java, testsrc/main/mondrian/test/BasicQueryTest.java, testsrc/main/mondrian/test/Main.java
@mkambol, @pamval here is backport of https://github.com/pentaho/mondrian/pull/639 and https://github.com/pentaho/mondrian/pull/643 to 3.10 (5.4) branch
=> [Sp-2459] - Backport of MONDRIAN-2279 - When a query is cancelled or times out, Mondrian may continue iterating over large tuple lists (5.4 Suite)

src/main/mondrian/server/Execution.java, testsrc/main/mondrian/olap/fun/CrossJoinTest.java, testsrc/main/mondrian/rolap/CancellationTest.java
@mkambol, here is the backport of https://github.com/pentaho/mondrian/pull/443 to 5.4. The check for timeout in Crossjoin was added in scope of another SP: https://github.com/pentaho/mondrian/pull/652/files#diff-5ec0bb38bb42f48c445dc7c435db6696R957
=> Sp-2469 - Backport of MONDRIAN-2425 - MDX will not stop at timeout for certain Analyzer reports with totals/subtotals (5.4 Suite)

testsrc/main/mondrian/olap/HierarchyBugTest.java
@mkambol, could you please take a look?
=> [MONDRIAN-1126] - tests demonstrate the issue isn't reproduced

testsrc/main/mondrian/olap/UtilTestCase.java
This will at least get the compile working w/ j8, but there will be lots of failed/error'd tests due to hashcode changes, etc.
@lucboudreau @kurtwalker
=> [CLEANUP]  Correcting compile error introduced w/ java 8 switch.

ivy.xml
Olap4j uses version 2.11.0, can evict 2.9.1 and cause build failure because current Mondrian code will not compile with XercesImpl 2.11.0
=> [CLEANUP] Exclude xercesImpl from olap4j

src/main/mondrian/spi/impl/JdbcDialectImpl.java, testsrc/main/mondrian/test/DialectTest.java
@mkambol @kurtwalker please merge
=> [MONDRIAN-2471] fix for processing sql columns containing dots

src/main/mondrian/olap/fun/CrossJoinFunDef.java, src/main/mondrian/rolap/HighCardSqlTupleReader.java, src/main/mondrian/rolap/SqlConstraintUtils.java, src/main/mondrian/rolap/SqlTupleReader.java, testsrc/main/mondrian/rolap/NativeEvalVirtualCubeTest.java, testsrc/main/mondrian/rolap/NonEmptyTest.java, testsrc/main/mondrian/test/Main.java
Adding support for native evaluation of sets in the context of a
virtual cube in which no cubes "fully join".  That is, if there is no
cube or cubes which are applicable to all dimensions in the native
targets.  For example, with a crossjoin of Warehouse and Gender, no
single cube joins to both.  Formerly native eval logic depended on the
presence of one or more fully joining cubes in order to find tuples,
with the assumption that the absence of a fully joining cube implies
that the resulting set will be empty.  That assumption is incorrect
when ValidMeasure is use (or other MDX expressions which changes
dimensional context).
This commit takes the approach of "grouping" native targets based on
their applicable cubes.  So with the above example, Gender and
Warehouse are grouped and …
=> [MONDRIAN-1599]  Virt Cube MDX mishandled w/ non-joining dims

src/main/mondrian/rolap/SqlTupleReader.java, testsrc/main/mondrian/rolap/NativeEvalVirtualCubeTest.java
The change for target grouping in SqlTupleReader (introduced with
5ee54f93) did not update the cache key generated for tuples, which
left the possibility that incorrect tuples would be retrieved from cache
if the target grouping for a query varied.
http://jira.pentaho.com/browse/MONDRIAN-1599
http://jira.pentaho.com/browse/MONDRIAN-2280
@lucboudreau
=> [MONDRIAN-2280]  Virt Cube MDX mishandled w/ non-joining dims

workbench/ivy.xml
security vulnerability CVE-2015-3253 - issue with groovy before version 2.4.4
=> [PPP-3536] - Updated groovy to version 2.4.7 due to CVE-2015-3253

workbench/ivy.xml
The fix is needed due to using java 1.8, and incompatibility of asm old version (is used by jersey) reading new java 1.8 features 
The following scope of repositories is upgraded(except webdetails): The list is sorted in the order of build team runs
https://github.com/pentaho/pentaho-reporting
https://github.com/pentaho/mondrian
https://github.com/pentaho/pentaho-kettle
https://github.com/pentaho/pentaho-mondrianschemaworkbench-plugins
https://github.com/pentaho/pentaho-platform
https://github.com/webdetails/cpf
https://github.com/pentaho/pentaho-metaverse
https://github.com/pentaho/pdi-platform-utils-plugin
https://github.com/pentaho/pentaho-data-profiling
https://github.com/pentaho/data-access
https://github.com/pentaho/big-data-plugin
https://github.com/pentaho/pentaho-data-refinery …
=> [BACKLOG-8388] - Upgrade Jersey to 1.19.1 across the suite for Java 8 compatibility

src/main/mondrian/util/ClassResolver.java
[BACKLOG-10022] - Fix for Mac issue where Thread.currentThread().getContextClassLoader() can return null. Found while working on getting analyzer running in osgi (on mac).
This is a common problem that we run into on mac. we can't be certain that Thread.currentThread().getContextClassLoader() will return a non-null value.
=> [BACKLOG-10022] - Fix for Mac issue where Thread.currentThread().getContextClassLoader() can return null

build.xml
- The Javassist version 3.20.0-GA is stored as bundle in maven
repo whereas javassist version 3.12.1.GA was stored as jar.
Changing the build.xml to use type as either jar or bundle while
retrieving from repo so that it can retrieve the new version of javassist.
=> [BACKLOG-10323] Standardizing on javassist version 3.20.0-GA

assemblies/psw-ce/src/assembly/assembly.xml
@kurtwalker @mkambol 
PSW assembly differs from the pre-maven one, moved pdi-dataservice-client jar back to plugins.
@kurtwalker please check for other libraries as other areas might be affected by the migration
=> [BACKLOG-12329] There is no connection to Pentaho Data Services in Schema Workbench in 7.1-QAT #66 build but it used to be in 7.0

mondrian/src/main/java/mondrian/rolap/RolapConnection.java
Prevent logging of JdbcPassword when there is a
MemoryLimitExceededException.
=> Fix for jira issue MONDRIAN-2542

pom.xml
In the 2.0.4 version of pentaho-ce-jar-parent-pom, the sonar properties are defined in the "sonar" Maven profile. In order for them to be overriden by the Jenkins job, they need to be defined global to the profile. The 7.1-SNAPSHOT version of pentaho-ce-jar-parent-pom defines the properties globally.
Contact me or @smaring for more details.
=> [ENGOPS-2734] Use the 7.1-SNAPSHOT parent pom to fix sonar properties.

mondrian/build.xml
This helps if you want intellij to compile to it's own out directory instead of target.
=> [CLEANUP] - resources should write to generated instead of target

src/main/mondrian/olap/fun/CrossJoinFunDef.java, testsrc/main/mondrian/rolap/NonEmptyTest.java
=> [SP-3338] Backport of MONDRIAN-328 - CrossJoin non empty optimizer eliminates calculated member (6.1 Suite)

src/main/mondrian/rolap/RolapCube.java, testsrc/main/mondrian/test/BasicQueryTest.java
=> [SP-3323] Backport of MONDRIAN-2245 - Mondrian omits primaryKeyTable if it is the right table of a Join (7.0 Suite)

mondrian/src/main/java/mondrian/rolap/RolapSchema.java, mondrian/src/main/java/mondrian/rolap/SchemaKey.java, mondrian/src/main/java/mondrian/rolap/agg/SegmentCacheManager.java
- SchemaKey became public
- key getter was added into RolapSchema
- SegmentCacheIndexRegistry now use SchemaKey
=> [MONDRIAN-2207] The segment cache index registry must use SchemaKey instead of only the checksum

assemblies/psw-ce/pom.xml, workbench/pom.xml
@lgrill-pentaho Please review. Tested change with the following jobs:
http://cerberusdmz.pentaho.com/job/8.0/job/mondrian-jar/52/consoleFull
http://cerberusdmz.pentaho.com/job/8.0/job/mondrian-workbench/49/consoleFull
http://cerberusdmz.pentaho.com/job/8.0/job/psw-assembly/50/consoleFull
You now see this in the log:
>14:19:20 14:19:20.723 [main] INFO  com.pentaho.VersionMerger - Updating 'pentaho-launcher.version' old value='8.0-SNAPSHOT' new value='8.0-QAT-81'
=> [CLEANUP] Update application launcher version property

mondrian/src/it/java/mondrian/rolap/agg/SegmentLoaderTest.java, mondrian/src/main/java/mondrian/rolap/agg/SegmentLoader.java
[PDI-16150] Pivot Table - Binary Type with another field - java.lang.RuntimeException: java.util.concurrent.ExecutionException
-fixed processing (ClassCastException) in kettle and in mondrian for binary data
kettle: https://github.com/pentaho/pentaho-kettle/pull/3849
=> [PDI-16150] Pivot Table - Binary Type with another field - java.lang.RuntimeException: java.util.concurrent.ExecutionException

mondrian/src/main/java/mondrian/rolap/RolapNativeFilter.java
We guessed that  this issue was caused by modification of between 6.1.0.6 and 6.1.0.7(That is, MONDRIAN-1803). 
In MONDRIAN-1803, FilterConstraint#isSupported was added, 
but this modification that SqlTupleReader#addLevelMembers method is not called in FilterConstraint#isSupported is the issue.
This issue cause that the return value of  SqlTupleReader#chooseAggStar is not 'null' in condition that we specify 'gender' which does not exist the aggrigation table. 
Eventually, MONDRIAN-2572 issue is happend.
@kolinus , @mchen-len-son  , @duarteteixeira  
Could you review this PR?
=> [MONDRIAN-2572] - Exclude filter fails on levels added from dimensions that are not part of the aggregate table definition

mondrian/src/it/java/mondrian/test/DrillThroughTest.java, mondrian/src/main/java/mondrian/rolap/RolapAggregationManager.java
cherry-pick of the fix for [ANALYZER-3433]: Drill through does not recognize level's nameColumn attribute
=> [SP-3664]: Backport of ANALYZER-3433 - Drill through does not recognize level's nameColumn attribute (7.1 Suite)

mondrian/src/it/java/mondrian/spi/DialectUtilTest.java, mondrian/src/it/java/mondrian/spi/impl/ImpalaDialectTest.java, mondrian/src/it/java/mondrian/spi/impl/JdbcDialectImplTest.java, mondrian/src/it/java/mondrian/spi/impl/MySqlDialectTest.java, mondrian/src/it/java/mondrian/spi/impl/OracleDialectTest.java, mondrian/src/it/java/mondrian/spi/impl/PostgreSqlDialectTest.java, mondrian/src/it/java/mondrian/test/Main.java, mondrian/src/main/java/mondrian/spi/DialectUtil.java, mondrian/src/main/java/mondrian/spi/impl/ImpalaDialect.java, mondrian/src/main/java/mondrian/spi/impl/MySqlDialect.java, mondrian/src/main/java/mondrian/spi/impl/OracleDialect.java, mondrian/src/main/java/mondrian/spi/impl/PostgreSqlDialect.java
The problem:
The fix: https://github.com/pentaho/pentaho-analyzer/commit/021a081d26fc51e13753ae5210073f38d5519b2d was not completed in full.
It covers the DBs that are not supported native evalution of the Matches MDX function.
In this case mondrian uses Java regex engine to evaluate matching.
By default, case-insensitive matching assumes that only characters in the US-ASCII charset are being matched (Please see https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html#UNICODE_CASE).
So it was added (?u) flag to allow unicode-aware case folding. Please see details in https://github.com/pentaho/pentaho-analyzer/commit/021a081d26fc51e13753ae5210073f38d5519b2d.
But we have also BDs with implemented support of native evalution of the Matches MDX function (was introduced in …
=> [ANALYZER-3488]: Unable to do case insensitive search with multi-byte characters in filter dialog and using the Matches operator

mondrian/src/it/java/mondrian/xmla/XmlaBasicTest.java, mondrian/src/it/java/mondrian/xmla/XmlaBasicTest.ref.xml, mondrian/src/main/java/mondrian/olap/type/TypeUtil.java
This is the cherry-pick of the fix for [MONDRIAN-2379]: Axes with empty sets cause NPE in XmlaHandler.
Used the origin commit: https://github.com/pentaho/mondrian/pull/256/commits/10f4a562985cdc467e14c24a6199c30194baeb47
Changed the unit test to get exactly described in the issue NPE.
=> [SP-3736]: Backport of MONDRIAN-2379 - Axes with empty sets cause NPE in XmlaHandler. (7.1 Suite)

mondrian/src/it/java/mondrian/test/NativeSetEvaluationTest.java, mondrian/src/main/java/mondrian/rolap/RolapResult.java
- missed axes evaluation was set
=> [MONDRIAN-2575] Sql WHERE clause is missing predicates when aggregated calculated member crossjoined w/ SetToStr() and Filter()

mondrian/src/it/java/mondrian/olap/fun/FunctionTest.java, mondrian/src/it/java/mondrian/olap/fun/PropertiesFunctionTest.java, mondrian/src/it/java/mondrian/test/Main.java, mondrian/src/it/java/mondrian/test/ParameterTest.java, mondrian/src/main/java/mondrian/olap/type/DimensionType.java
The cause of the bug:
In mondrian schema a dimention can contain many hierarchies.
In mondrian schema it's allowed hierarchies without name attribute. In this case the hierarchy has the same name as its dimension.
When expression with a dimention is been parsing and resolving and it needs to get the hierarchy of this dimention, then it's returned null for the case when the dimention contains two hierarchy.
This is incorrect because we ignore the hierarchies with the same name as dimention name.
An this is the cause of the issue because the return type for the member Property function is taken exactly from this member resolved hierarchy levels.
Please see:
https://github.com/pentaho/mondrian/blob/master/mondrian/src/main/java/mondrian/olap/fun/PropertiesFunDef.java#L113 …
=> [MONDRIAN-2402]: Mondrian incorrectly resolves <String> Generate(<Set>, <String>, <String>) to <Set> Generate(<Set>, <Set>, <Symbol>)

mondrian/build.xml, mondrian/pom.xml, mondrian/src/it/resources/mondrian/test/loader/SteelWheels.mysql.sql, mondrian/src/main/java/mondrian/olap/MondrianServer.java, mondrian/src/main/java/mondrian/rolap/RolapSchema.java, mondrian/src/main/java/mondrian/server/MondrianServerRegistry.java
@pentaho/2-1b please review. I could not duplicate the original issue but found some broken CREATE statements and fixed them while investigating. mediumtext column types are not available when the ENGINE type is MEMORY in MySQL.
=> [BACKLOG-18450] remove or fix version specific integration tests in Mondrian

assemblies/psw-ce/src/main/resources/workbench.command
- added license to the command file
=> [PSW-229] Script files don't have an header with Copyright data

mondrian/src/it/java/mondrian/test/AccessControlTest.java, mondrian/src/main/java/mondrian/olap/RoleImpl.java
This is the cherry-pick of the fix for [MONDRIAN-2586]: Ragged dimension members are not visible when using a single role
Fixed. Added unit test to cover changes.
=> [SP-3819]: Backport of MONDRIAN-2586 - Ragged dimension members are not visible when using a single role (7.1 Suite)

mondrian/src/it/java/mondrian/rolap/RolapSchemaTest.java, mondrian/src/it/java/mondrian/rolap/RolapUtilTest.java, mondrian/src/it/java/mondrian/test/Main.java, mondrian/src/it/java/mondrian/test/SchemaTest.java, mondrian/src/main/java/mondrian/rolap/RolapSchema.java, mondrian/src/main/java/mondrian/rolap/RolapUtil.java, mondrian/src/main/java/mondrian/rolap/agg/AggregationManager.java
This is the cherry-pick of the fix for [MONDRIAN-1073]: Two cubes operating on same fact table gives wrong WHERE clause
There are fix, unit tests and the integration test.
=> [SP-3921]: Backport of MONDRIAN-1073 - Two cubes operating on same fact table gives wrong WHERE clause (7.1 Suite)

mondrian/src/it/java/mondrian/rolap/RolapSchemaTest.java, mondrian/src/it/java/mondrian/rolap/RolapUtilTest.java, mondrian/src/it/java/mondrian/test/Main.java, mondrian/src/it/java/mondrian/test/SchemaTest.java, mondrian/src/main/java/mondrian/rolap/RolapSchema.java, mondrian/src/main/java/mondrian/rolap/RolapUtil.java, mondrian/src/main/java/mondrian/rolap/agg/AggregationManager.java
This is the cherry-pick of the fix for [MONDRIAN-1073]: Two cubes operating on same fact table gives wrong WHERE clause
There are fix, unit tests and the integration test.
=> [SP-3922]: Backport of MONDRIAN-1073 - Two cubes operating on same fact table gives wrong WHERE clause (8.0 Suite)

mondrian/src/it/java/mondrian/olap/fun/CrossJoinTest.java, mondrian/src/it/java/mondrian/test/Main.java, mondrian/src/it/java/mondrian/test/TupleListTest.java, mondrian/src/it/java/mondrian/util/CancellationCheckerTest.java, mondrian/src/main/java/mondrian/olap/fun/CrossJoinFunDef.java, mondrian/src/main/java/mondrian/olap4j/MondrianOlap4jCellSetAxis.java, mondrian/src/main/java/mondrian/util/CancellationChecker.java
This is the cherry-pick of the commit for [MONDRIAN-2534]: Mondrian CancellationChecker.checkCancelOrTimeout does not terminate thread
Fixed according to the comment in the jira, added unit tests.
Placed a Locus in the execution context for MondrianOlap4jCellSetAxis on getting axis positions size.
Fixed checksyle issues.
=> [SP-3884]: Backport of MONDRIAN-2534 - Mondrian CancellationChecker.checkCancelOrTimeout does not terminate thread (8.0 Suite)

mondrian/src/it/java/mondrian/olap/fun/CrossJoinTest.java, mondrian/src/it/java/mondrian/test/Main.java, mondrian/src/it/java/mondrian/test/TupleListTest.java, mondrian/src/it/java/mondrian/util/CancellationCheckerTest.java, mondrian/src/main/java/mondrian/olap/fun/CrossJoinFunDef.java, mondrian/src/main/java/mondrian/olap4j/MondrianOlap4jCellSetAxis.java, mondrian/src/main/java/mondrian/util/CancellationChecker.java
This is the cherry-pick of the fix for [MONDRIAN-2534]: Mondrian CancellationChecker.checkCancelOrTimeout does not terminate thread
Fixed according to the comment in the jira, added unit tests.
Placed a Locus in the execution context for MondrianOlap4jCellSetAxis on getting axis positions size.
Fixed checksyle issues.
=> [SP-3883]: Backport of MONDRIAN-2534 - Mondrian CancellationChecker.checkCancelOrTimeout does not terminate thread (7.1 Suite)

mondrian/src/it/java/mondrian/test/AccessControlTest.java, mondrian/src/main/java/mondrian/rolap/RolapCube.java, mondrian/src/main/java/mondrian/rolap/RolapDimension.java
**Cause of the problem:**
**[Measures]** dimension access for Role should be placed in `dimensionGrants` map, if **[Measures]** hierarchy has access modifier in Role.
**[Measures]** dimension acts as a key of `dimensionGrants` map.
Since **[Measures]** dimension is represented by `RolapDimention` and this one has no overridden `equals` method but only base in `OlapElementBase`, we can put only one **[Measures]** dimension object into `dimensionGrants`.
So e.g. for two cubes with restrictions on **[Measures]** dimensions we will have only one item in `dimensionGrants`.
But when we get access to **[Measures]** dimension to decide to display measures or not, **[Measures]** dimension objects are compared by object identity (please see …
=> [MONDRIAN-2603]: Measures completely disappear from a second cube defined in the same schema when measures are constrained using Mondrian role

mondrian/src/it/java/mondrian/util/FormatTest.java, mondrian/src/main/java/mondrian/rolap/agg/SegmentLoader.java, mondrian/src/main/java/mondrian/util/Format.java
[PDI-16761] In Model View, integer type numerical value more than 17 digits is rounded off
added correct processing BigDecimal without losing precision
=> [PDI-16761] In Model View, integer type numerical value more than 17 digits is rounded off

mondrian/src/it/java/mondrian/spi/impl/JdbcDialectImplTest.java, mondrian/src/it/java/mondrian/spi/impl/MicrosoftSqlServerDialectTest.java, mondrian/src/main/java/mondrian/spi/impl/MicrosoftSqlServerDialect.java, mondrian/src/main/java/mondrian/spi/impl/MySqlDialect.java
This is the cherry-pick of the fix for [MONDRIAN-1233]: MySQL/MS SQL Dialect needs to override Dialect.quoteBooleanLiteral (#999)
Fixed, added unit tsts.
=> [SP-4024]: Backport of MONDRIAN-1233 - MySQL/MS SQL Dialect needs to override Dialect.quoteBooleanLiteral (8.0 Suite)

mondrian/src/it/java/mondrian/spi/impl/JdbcDialectImplTest.java, mondrian/src/it/java/mondrian/spi/impl/MicrosoftSqlServerDialectTest.java, mondrian/src/main/java/mondrian/spi/impl/MicrosoftSqlServerDialect.java, mondrian/src/main/java/mondrian/spi/impl/MySqlDialect.java
This is the cherry-pick of the fix for [MONDRIAN-1233]: MySQL/MS SQL Dialect needs to override Dialect.quoteBooleanLiteral (#999)
Fixed, added unit tsts.
=> [SP-4023]: Backport of MONDRIAN-1233 - MySQL/MS SQL Dialect needs to override Dialect.quoteBooleanLiteral (7.1 Suite)

assemblies/psw-ce/pom.xml
@pentaho/2-1b depoends on https://github.com/pentaho/pentaho-mondrianschemaworkbench-plugins/pull/23
=> [BACKLOG-13813] - Downstream updates

mondrian/pom.xml
@pentaho/x-wing 
Depends on https://github.com/pentaho/maven-parent-poms/pull/53
=> [ENGOPS-2977] Removing build helper plugin version

workbench/src/main/java/mondrian/gui/JdbcMetaData.java
Expectation was that jdbc driver would be limiting the catalog because the database connection includes the database on the jdbc url.  This is not the case with snowflake, so we need to explicitly give jdbc the catalog with each request for metadata.
=> [BACKLOG-29977] - including catalogName in all calls to jdbc metadata

mondrian/src/main/java/mondrian/spi/impl/JdbcDialectImpl.java
Mondrian iterates through each supported dialect when looking for
a dialect appropriate for the current connection.  For some dbtypes
(redshift, impala, hive, etc.) we fall back to attempting to get
the type via "select version()".  For any db that doesn't support
version(), we would log the stacktrace.
Removing the stacktrace from debug logging, since it's misleading.
The error is expected and allowable in such cases, and just means
that the dialect is not correct for the given connection.
https://jira.pentaho.com/browse/BACKLOG-30300
=> [BACKLOG-30300]  PSW/Mondrian Error on debug log file w/ some db types

mondrian/pom.xml, workbench/pom.xml
@pentaho/tatooine @pentaho-lmartins @wseyler 
* [PDI-17794] Removed version references due to maven-parent-poms controlling that aspect
This pull request is part of a series of pull requests:
- https://github.com/pentaho/maven-parent-poms/pull/137
- https://github.com/pentaho/adaptive-execution-layer/pull/3
- https://github.com/pentaho/big-data-plugin/pull/1682
- https://github.com/webdetails/cdf/pull/1075
- https://github.com/pentaho/commons-ee/pull/1
- https://github.com/webdetails/cpf/pull/144
- https://github.com/webdetails/cpk/pull/82
- https://github.com/pentaho/data-access/pull/1060
- https://github.com/pentaho/maven-project-archetypes/pull/16
- https://github.com/pentaho/maven-project-archetypes-ee/pull/35
- https://github.com/pentaho/modeler/pull/356
- …
=> [PDI-17794] Warnings in Spoon console due to wrong version of log4j

mondrian/src/it/java/mondrian/rolap/cache/SegmentCacheIndexImplTest.java, mondrian/src/it/java/mondrian/test/Main.java, mondrian/src/main/java/mondrian/rolap/cache/SegmentCacheIndexImpl.java
Merge Masters: @pentaho-lmartins  and @smmribeiro
Cherry-picks:
* https://github.com/Pentaho/mondrian/commit/e967bf0ed1f43e11d4d6bcf1d89600a8ae53cf9b
=> [SP-5310] Backport of MONDRIAN-2674 - NullPointerException on Mondrian.rolap.cache.SegmentCacheIndexImpl (8.3 Suite)

workbench/src/main/java/mondrian/gui/JdbcMetaData.java
@pentaho/millenniumfalcon ready for review and merge
This was a problem caused by this change
https://github.com/pentaho/mondrian/commit/93d53121aa3376f16c6cba05b8491cd2e021f8a9#diff-fbee9ed88e5bf6e584e38195bc261285R205
Due to this driver implementation
https://github.com/rjnichols/jtds/blob/master/src/main/net/sourceforge/jtds/jdbc/JtdsDatabaseMetaData.java#L3587
=> [BACKLOG-31938] - Schema Workbench - Errors when connecting to a DB

mondrian/pom.xml, pom.xml
@pentaho/tatooine @pentaho-lmartins @ssamora 
* [PDI-17775] Removing version reference, maven parent pom will control version.
This PR is a part of a series of PR to upgrade commons-vfs2 and fix VFS issues with HTTP:
- https://github.com/pentaho/apache-vfs-browser/pull/60
- https://github.com/pentaho/big-data-plugin/pull/1929
- https://github.com/webdetails/cpk/pull/85
- https://github.com/pentaho/data-access/pull/1083
- https://github.com/pentaho/maven-parent-poms/pull/185
- https://github.com/pentaho/mondrian/pull/1177
- https://github.com/pentaho/pdi-jms-plugin/pull/73
- https://github.com/pentaho/pdi-platform-utils-plugin/pull/102
- https://github.com/pentaho/pdi-plugins-ee/pull/139
- https://github.com/pentaho/pdi-sap-hana-bulk-loader-plugin/pull/82
- …
=> [PDI-17775] Process Files step no longer supports HTTP scheme

mondrian/pom.xml
Integration tests were failing due to a mismatch
of the currency symbol.
=> [TEST] Explicitly setting language US_en for locale.

mondrian/src/it/java/mondrian/calc/impl/ArrayTupleListTest.java, mondrian/src/it/java/mondrian/test/BasicQueryTest.java, mondrian/src/main/java/mondrian/calc/impl/ArrayTupleList.java
to make the threshold = number of tuples rather than members.
https://jira.pentaho.com/browse/MONDRIAN-2662
=> [MONDRIAN-2662] better handling of the result.limit in ArrayTupleList

mondrian/README.md, mondrian/pom.xml, mondrian/src/it/java/mondrian/rolap/aggmatcher/SpeciesNonCollapsedAggTest.java
1)  For embedded MySQL, need to provide default cnf file.  (Same fix applied to Pentaho Analyzer).
2)  Fix integration test failure caused by table name casing difference in Mondrian schema and what actually gets created in Windows MySQL (default lower_case_table_names=1)
=> [TESTS] Fix integration testing on Windows.

mondrian/src/main/java/mondrian/spi/impl/SnowflakeDialect.java
SELECT clause with an alias in order to use it in an ORDER BY clause.
=> [MONDRIAN-2682] Snowflake does not require a column to appear in the

mondrian/src/main/java/mondrian/spi/impl/SnowflakeDialect.java
SELECT clause with an alias in order to use it in an ORDER BY clause.
This commit is a cherry-pick from master bc5947d77
=> [SP-5640] Snowflake does not require a column to appear in the

mondrian/src/main/java/mondrian/spi/impl/SnowflakeDialect.java
SELECT clause with an alias in order to use it in an ORDER BY clause.
This commit is a cherry-pick from master bc5947d77
=> [SP-5641] Snowflake does not require a column to appear in the

mondrian/src/it/java/mondrian/rolap/VirtualCubeTest.java, mondrian/src/main/java/mondrian/rolap/RolapCube.java, mondrian/src/main/java/mondrian/rolap/RolapSchema.java
the virtual cube's definition; was defaulting to base cube.
=> [MONDRIAN-1060] Set visibility of calculated members in virtual cube per

mondrian/src/it/java/mondrian/rolap/VirtualCubeTest.java, mondrian/src/main/java/mondrian/rolap/RolapCube.java, mondrian/src/main/java/mondrian/rolap/RolapSchema.java
the virtual cube's definition; was defaulting to base cube.
This commit is a cherry-pick from master c92b3519
=> [SP-5990] Set visibility of calculated members in virtual cube per

mondrian/src/it/java/mondrian/rolap/VirtualCubeTest.java, mondrian/src/main/java/mondrian/rolap/RolapCube.java, mondrian/src/main/java/mondrian/rolap/RolapSchema.java
the virtual cube's definition; was defaulting to base cube.
This commit is a cherry-pick from master c92b3519
=> [SP-5991] Set visibility of calculated members in virtual cube per

mondrian/src/main/java/mondrian/olap/IdBatchResolver.java, mondrian/src/main/java/mondrian/olap/fun/AggregateFunDef.java
@smmribeiro 
@renato-s 
@bcostahitachivantara 
We used SchemaReader.getLevelCardinality (gets the size of the elements loaded to cache for that level) instead of getting all elements and counting them.
=> [MONDRIAN-2720] - GetMemberChildren should not return actual members for distinct count optimization

mondrian/src/main/java/mondrian/olap/IdBatchResolver.java, mondrian/src/main/java/mondrian/olap/fun/AggregateFunDef.java
=> [SP-6336] - Backport of MONDRIAN-2720 - GetMemberChildren should not return actual members for distinct count optimization (9.3 Suite)

mondrian/src/main/java/mondrian/rolap/MemberCacheHelper.java, mondrian/src/main/java/mondrian/rolap/RolapMember.java
@smmribeiro 
@renato-s 
@bcostahitachivantara 
Fixing problem found in integration tests when checking cache elements are present.
=> [SP-6337] - Backport of MONDRIAN-2733 - Performance issues when Mondrian is dealing with large GetMemberChildren queue (9.3 Suite)

workbench/src/main/java/mondrian/gui/PreferencesDialog.java
[BACKLOG-40978] 10.2: Default driver class used is org.gjt.mm.mysql.driver instead of recommended com.mysql.jdbc.Driver
[BACKLOG-40978]: https://hv-eng.atlassian.net/browse/BACKLOG-40978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-40978] 10.2: Default driver class used is org.gjt.mm.mysql.driver instead of recommended com.mysql.jdbc.Driver

assemblies/psw-ce/pom.xml
- Update groovy minor version to 2.4.21 to address CVE-2020-17521
- exclude transitive dependencies and their vulnerabilities
JIRA: https://hv-eng.atlassian.net/browse/PPP-4784
PR Set:
- https://github.com/pentaho/pentaho-platform/pull/5680
- https://github.com/pentaho/pentaho-reporting/pull/1676
- https://github.com/pentaho/big-data-plugin/pull/2584
- https://github.com/pentaho/pentaho-big-data-ee/pull/612
- https://github.com/pentaho/mondrian/pull/1386
=> [PPP-4784] Vulnerable Component: groovy

.github/workflows/trx-agent-scan.yaml
=> Add workflow

mondrian/src/main/resources/mondrian.xsd
- VirtualCubeDimensionType now extends CubeDimensionType. 
- Updated formatter classes references in documentation to refer to non deprecated ones.
=> fix(XSD): fixed VirtualCubeDimensionType and deprecated class references [SME-285]

mondrian/src/main/resources/mondrian.xsd
Merge only after [CubeDimensionType json deserialization ](https://github.com/pentaho/semantic-model-editor/blob/53e84f0799c88d8a8db7d753634446667853f2c6/backend/src/main/java/com/pentaho/plugin/semantic_model_editor/mapper/model/CubeDimensionTypeDeserializer.java#L19-L25)has been fixed.
=> fix(XSD): Prevent `PrivateDimensionType` to be used as dimensions of a Schema. [SME-365]

mondrian/src/main/resources/mondrian.xsd
https://hv-eng.atlassian.net/browse/SME-313
Having simple types referenced at elements, introduces issues at jaxb generated code at Semantic Model Editor project.
SME requires the injection of a new smeID atribute at the generated types, that is not possible with the primitive String type.
=> fix: replace string simple type usages with a complex type [SME-313]

mondrian/src/main/resources/mondrian.xsd
https://hv-eng.atlassian.net/browse/SME-313
Fix FormulaType definition: simple types as base must be used inside <xs:simpleContent>.
When <complexContent> is used, the base type must be a complexType.
=> fix: fix FormulaType definition [SME-313]

mondrian/src/main/java/mondrian/tui/MockHttpServletRequest.java
[BACKLOG-41287]-Upgrading Mondrian from Java EE to  Jakarta EE to be compatiable with Tomcat-10.X
[BACKLOG-41287]: https://hv-eng.atlassian.net/browse/BACKLOG-41287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-41287]-Upgrading Mondrian from Java EE to  Jakarta EE to be compatiable with Tomcat-10.X

mondrian/src/main/resources/mondrian.xsd
Add validations to ensure element names can't be only white spaces, so things like ` name` won't be a valid value
=> feat: add element name validation to avoid having only white spaces [SME-529]

mondrian/src/main/resources/mondrian.xsd
Allow for empty strings in `ElementNameType`. Now only strings with only white spaces will be considered invalid (see https://github.com/pentaho/mondrian/pull/1437)
=> fix: allow empty string in element name type [SME-529]

mondrian/src/it/java/mondrian/rolap/SqlConstraintUtilsTest.java, mondrian/src/it/java/mondrian/spi/impl/MicrosoftSqlServerDialectTest.java, mondrian/src/it/java/mondrian/spi/impl/OracleDialectTest.java, mondrian/src/it/java/mondrian/test/DrillThroughTest.java, mondrian/src/it/java/mondrian/test/Main.java, mondrian/src/it/java/mondrian/test/UnicodeSpecialCharactersTest.java, mondrian/src/main/java/mondrian/spi/impl/MicrosoftSqlServerDialect.java, mondrian/src/main/java/mondrian/spi/impl/OracleDialect.java
Ensure that unicode strings are processed correctly for SQL Server and Oracle.
When used in conditions, the SQL queries were not yielding the expected results.
See https://hv-eng.atlassian.net/browse/MONDRIAN-990 and https://hv-eng.atlassian.net/browse/MONDRIAN-990?focusedCommentId=1650724 for more details (the proposed solution is similar to the one implement in eazyBI)
Demo video with sql server connection before changes:
https://github.com/user-attachments/assets/fe5c86f0-7857-42bf-944c-9fb7f7b91478
Demo video with sql server connection after changes:
https://github.com/user-attachments/assets/5cf67026-5ff7-4597-a0fe-ea10bb4c8706
=> [MONDRIAN-990] fix: ensure unicode strings are processed correctly

mondrian/build.xml
This pull request makes a minor change to the build process by updating the `mondrian/build.xml` file. The main change is switching the `fork` attribute from "no" to "true" for a Java execution task, which will cause the Java process to run in a separate JVM.
Forking starts the Java process separately, allowing better compatibility with newer JVM options
=> [BACKLOG-43902]-Java 21 : compatibility check for Pentaho and fix Build and Run time issues while building / testing
